import Danhmuc from "@/components/Danhmuc";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Image from "next/image";
import router from "next/router";

import icon_other from "../../../assets/icon/ic_dodientu/ic_hangdienthoai/other.svg";
import Display_product_horizontal from "@/components/Display_product_horizontal";
//import css file Slider
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";
import ReactPaginate from "react-paginate";

import item_list_phukien, {
  phukien,
} from "../../../components/obj_data_raw/List_Phukien";
import { API_get_Dodientu } from "@/service/userService";

const list_phukien: phukien[] = item_list_phukien;

const phu_kien = () => {
  const settings_slider = {
    dots: true,
    arrows: false,
    infinite: true,
    speed: 500,
    slidesToShow: 5,
    slidesToScroll: 4,
    autoplay: false,
    delay: 300,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 700,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 530,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        },
      },
    ],
  };
  const [itemPhukien, setitemPhukien] = useState<any[]>([]);
  const [pagehientai, setpagehientai] = useState<number>(1);
  const [totalpages, setTotalPages] = useState<number>(1);
  const [loaiphukien, setloaiphukien] = useState<string>();

  useEffect(() => {
    fetchDataProduct();
  }, [pagehientai, loaiphukien]);
  const fetchDataProduct = async () => {
    if (!loaiphukien) {
      try {
        const build_data = {
          type: "phukien",
          soluong: 10,
          loaiphukien: "ALL",
          pagehientai: pagehientai,
        };
        const response = await API_get_Dodientu(build_data);
        setitemPhukien(response.phukien);
        setTotalPages(response.totalpages);
        console.log("check response: ", response);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    } else {
      fetchDataProduct_filter();
    }
  };
  const fetchDataProduct_filter = async () => {
    try {
      const build_data = {
        type: "phukien",
        soluong: 10,
        loaiphukien: loaiphukien,
        pagehientai: pagehientai,
      };
      const response = await API_get_Dodientu(build_data);
      setitemPhukien(response.phukien);
      setTotalPages(response.totalpages);
      console.log("check response: ", response);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };
  const [filteredHang, setFilteredHang] = useState<number | null>(null);
  const Filter_Phukien = async (key: number, loaiphukien: string) => {
    setitemPhukien([]);
    if (filteredHang === key) {
      setFilteredHang(null);
      setloaiphukien(undefined);
      setpagehientai(1);
    } else {
      setFilteredHang(key);
      setloaiphukien(loaiphukien);
      setpagehientai(1);
    }
  };
  const Handle_TatcaHang = async () => {
    setitemPhukien([]);
    setFilteredHang(0);
    setloaiphukien(undefined);
    setpagehientai(1);
    fetchDataProduct();
  };
  const handlePageClick = (event: any) => {
    const selected = event.selected + 1;
    setpagehientai(selected);
  };

  return (
    <div className="bg-gray-100">
      <Head>
        <title>2Hand Market - Phụ kiện</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon_2handmarket.png" />
      </Head>
      <Header />
      {/* Điều hướng */}
      <div className="h-[50px] w-full flex items-center justify-center mt-2">
        <div className="h-full w-[960px] bg-white text-lg flex items-center p-1 rounded-lg shadow-md">
          <Danhmuc />
          <p className="h-full w-auto flex items-center ml-3">
            Trang chủ / Đồ điện tử / Phụ kiện
          </p>
        </div>
      </div>
      <div className="text-lg font-bold w-full flex items-center justify-center mt-2">
        <div className="h-[30px] w-[960px] overflow-hidden">
          <p className="running-text">
            Mua bán phụ kiện qua sử dụng thuận tiện, nhanh chóng
          </p>
        </div>
      </div>
      {/* Option */}
      <div className="h-auto w-full flex items-center justify-center mt-3">
        <div className="bg-white shadow-sm h-full w-[960px] px-2 pt-2">
          <div className="w-full flex items-center place-content-between">
            <p className="text-lg font-bold">Khám phá các sản phẩm phụ kiện</p>
            <p
              className="text-lg font-bold text-mauxanhtroi underline cursor-pointer hover:opacity-75"
              onClick={() => Handle_TatcaHang()}
            >
              Xem tất cả
            </p>
          </div>
          <div className="h-[140px] w-full pt-3">
            <div className="h-full w-full">
              <Slider {...settings_slider}>
                {list_phukien &&
                  list_phukien.map((item: phukien) => {
                    return (
                      <div key={item.key} className="h-full w-[150px]">
                        <div className="h-[70px] w-full flex items-center justify-center">
                          <div
                            onClick={() => Filter_Phukien(item.key, item.type)}
                            className={`h-[70px] w-[70px] flex items-center justify-center bg-gray-100 rounded-full hover:bg-gray-300 ${
                              item.key === filteredHang ? "bg-gray-300" : ""
                            }`}
                          >
                            {item.key === 6 && (
                              <Image
                                src={item.key === 6 && icon_other}
                                alt="icon"
                                className="h-[50px] w-[50px] cursor-pointer"
                              />
                            )}
                            <p
                              hidden={item.key === 6}
                              className="text-base uppercase"
                            >
                              {item.type}
                            </p>
                          </div>
                        </div>
                        <p className="h-[30px] w-full flex justify-center cursor-pointer p-1">
                          {item.label}
                        </p>
                      </div>
                    );
                  })}
              </Slider>
            </div>
          </div>
        </div>
      </div>
      <div className="h-auto w-full flex flex-col items-center justify-center mt-3">
        <div className="bg-white shadow-sm h-auto min-h-[360px] max-h-[1620px] w-[960px] p-2 overflow-x-hidden">
          {itemPhukien &&
            itemPhukien.map((item: any, index: any) => {
              return (
                <div key={index}>
                  <Display_product_horizontal item={item} />
                </div>
              );
            })}
        </div>
        <div className="bg-gray-100 mt-5 mb-3">
          <ReactPaginate
            forcePage={pagehientai - 1}
            breakLabel="..."
            nextLabel="Sau >"
            onPageChange={handlePageClick}
            pageRangeDisplayed={2}
            pageCount={totalpages}
            previousLabel="< Trước"
            renderOnZeroPageCount={null}
            //css
            pageClassName="h-full w-[35px] flex items-center justify-center text-lg border border-blue-500 text-blue-500"
            pageLinkClassName="page-link"
            previousClassName="h-full w-[100px] bg-gray-100 rounded-l-md border-2 border-blue-500 flex items-center justify-center text-lg text-blue-500 cursor-pointer"
            previousLinkClassName="page-link"
            nextClassName="h-full w-[100px] bg-gray-100 rounded-r-md border-2 border-blue-500 flex items-center justify-center text-lg text-blue-500 cursor-pointer"
            nextLinkClassName="page-link"
            breakClassName="h-full w-[35px] flex items-center justify-center border border-blue-500 text-blue-500"
            breakLinkClassName="page-link"
            containerClassName="h-[40px] flex items-center justify-center space-x-2"
            activeClassName="bg-blue-500 text-white"
          />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default phu_kien;
