import React, { useState } from 'react';
import Head from "next/head";
import Image from 'next/image';
import axios from 'axios';
import { searchYoutube } from '@/service/userService';
require('dotenv').config();

const TestYoutube: React.FC = () => {
    const [query, setQuery] = useState('');
    const [results, setResults] = useState<any[]>([]);

    const handleSearch = async () => {
        try {
            const response = await searchYoutube(query, 1, 5);
            setResults(response);
        } catch (error) {
            console.error('Error fetching data from YouTube API', error);
        }
    }

    return (
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', marginTop: '50px' }}>
            <Head>
                <title>Youtube</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/icon_2handmarket.png" />
            </Head>
            <h1>YouTube Search</h1>
            <div style={{ display: 'flex', justifyContent: 'center', width: '100%' }}>
                <input
                    type="text"
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder="Search YouTube"
                    style={{ padding: '10px', width: '300px', borderRadius: '5px', border: '1px solid #ccc', outlineStyle: 'none' }}
                />
                <button
                    onClick={handleSearch} style={{ padding: '10px', marginLeft: '10px', borderRadius: '5px', border: 'none', backgroundColor: '#007BFF', color: 'white' }}>
                    Search
                </button>
            </div>
            <div style={{ marginTop: '20px', width: '80%' }}>
            {results.map((item) => (
                <div key={item.songId} style={{ marginBottom: '20px', borderBottom: '1px solid #ccc', paddingBottom: '10px' }}>
                    <div className="flex items-center mb-2 space-x-2">
                        <div className="">
                            <Image
                                src={item.thumbnail}
                                alt={item.fullName}
                                style={{ width: '140px', height: '80px', objectFit: 'cover', borderRadius: '5px' }}
                                width={140}
                                height={80}
                            />
                        </div>
                        <div className="">
                            <h3>{item.fullName}</h3>
                            <p>{item.username}</p>
                        </div>
                    </div>
                    <div style={{ display: 'flex', gap: '10px', justifyContent: 'center' }}>
                        {/* Video 1 */}
                        <div style={{ position: 'relative', width: '50%', paddingTop: '28.125%' }}>
                            <iframe
                                style={{
                                    position: 'absolute',
                                    top: 0,
                                    left: 0,
                                    width: '100%',
                                    height: '100%',
                                }}
                                src={`${item.trackUrlEmbed}?vq=hd1080?cc_load_policy=0`}
                                frameBorder="0"
                                allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                allowFullScreen
                                title={`${item.fullName}-video1`}
                            ></iframe>
                        </div>
                        {/* Video 2 */}
                        <div style={{ position: 'relative', width: '50%', paddingTop: '28.125%' }}>
                            <iframe
                                style={{
                                    position: 'absolute',
                                    top: 0,
                                    left: 0,
                                    width: '100%',
                                    height: '100%',
                                }}
                                src={`${item.trackUrlNoCookie}`}
                                frameBorder="0"
                                allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                allowFullScreen
                                title={`${item.fullName}-video2`}
                            ></iframe>
                        </div>
                    </div>
                </div>
))}
            </div>
        </div>
    );
};

export default TestYoutube;

