import Head from "next/head";
import { useRef, useEffect, useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styles from "../styles/Home.module.css";
import { API_getAllcollection, API_get_Dodientu } from "@/service/userService";
import router from "next/router";
import Danhmuc from "@/components/Danhmuc";
import Display_product_vertical from "@/components/Display_product_vertical";
import { delay, motion } from "framer-motion";
import Image from "next/image";
import dealbatngan from "../assets/img/banner_dealbatngan.jpg";
import doSV from "../assets/img/banner_doSVthich.jpg";
import thuDienthoai from "../assets/img/banner_thudienthoai2h.jpg";
import trogantruong from "../assets/img/banner_trogantruong.png";
import daytinngay from "../assets/img/banner_daytinngay.png";

import icon_lg_hoctap from "../assets/img/icon_lg_hoctap.jpg";
import icon_lg_canhan from "../assets/img/icon_lg_canhan.png";
import icon_lg_dodientu from "../assets/img/icon_lg_dodientu.png";
import icon_lg_giaitri from "../assets/img/icon_lg_giaitri.png";
import icon_lg_noithat from "../assets/img/icon_lg_noithat.png";
import icon_lg_thucung from "../assets/img/icon_lg_thucung.png";
import icon_lg_tulanh from "../assets/img/icon_lg_tulanh.png";
import icon_lg_xeco from "../assets/img/icon_lg_xeco.png";

//import css file Slider
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";

type DataInfor = {
  _id: string;
  name: string;
  account: string;
  address: string;
  role: string;
};

import item_danhmuc, {
  danhmuc,
  sub_danhmuc,
} from "../components/obj_data_raw/Danhmuc_raw";
const danhmuc: danhmuc[] = item_danhmuc;

const Home = () => {
  useEffect(() => {
    fetchDataProduct();
  }, []);

  const [tindang_ganday, setTindang_ganday] = useState<any[]>([]);
  const fetchDataProduct = async () => {
    try {
      const response = await API_getAllcollection();
      //sort tất cả theo thời gian mới nhất
      const sort_response = response.all_collection
        .slice()
        .sort(
          (a: any, b: any) =>
            new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        );
      setTindang_ganday(sort_response);
    } catch (error) {
      console.error("Error fetch data: ", error);
    }
  };

  const settings_slider = {
    dots: true,
    arrows: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    delay: 300,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 700,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 530,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        },
      },
    ],
  };

  return (
    <div className="bg-gray-100">
      <Head>
        <title>2Hand Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon_2handmarket.png" />
      </Head>

      <Header />

      {/* Banner */}
      <div className="h-[320px] w-full flex items-center justify-center">
        <div className="bg-white shadow-sm h-full w-[960px] px-2 pt-1">
          <div className="h-[50px] w-full">
            <Danhmuc />
          </div>
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0, transition: { duration: 0.3 } }}
          >
            <Slider {...settings_slider}>
              <Image
                src={dealbatngan}
                alt=""
                className="h-full w-full rounded-md"
              />
              <Image src={doSV} alt="" className="h-full w-full rounded-md" />
              <Image
                src={thuDienthoai}
                alt=""
                className="h-full w-full rounded-md"
              />
              <Image
                src={trogantruong}
                alt=""
                className="h-full w-full rounded-md"
              />
              <Image
                src={daytinngay}
                alt=""
                className="h-fit w-full rounded-md"
              />
            </Slider>
          </motion.div>
        </div>
      </div>
      {/* Khám phá danh mục */}
      <div className="h-[290px] w-full flex items-center justify-center mt-3">
        <div className="bg-white shadow-sm h-full w-[960px] px-2 pt-2">
          <p className="text-lg font-bold">Khám phá danh mục</p>
          <div className="h-[250px] w-full pt-2">
            <div className="h-[50%] w-full flex items-center">
              {danhmuc &&
                danhmuc.slice(0, 4).map((item_main: danhmuc) => {
                  return (
                    <div
                      key={item_main.key}
                      className="h-full w-1/4"
                      onClick={() => router.push(`${item_main.link}`)}
                    >
                      <div className="h-[80px] w-full flex items-center justify-center">
                        <Image
                          src={
                            item_main.key === 0
                              ? icon_lg_hoctap
                              : "" || item_main.key === 1
                              ? icon_lg_xeco
                              : "" || item_main.key === 2
                              ? icon_lg_dodientu
                              : "" || item_main.key === 3
                              ? icon_lg_noithat
                              : "" || item_main.key === 4
                              ? icon_lg_tulanh
                              : "" || item_main.key === 5
                              ? icon_lg_canhan
                              : "" || item_main.key === 6
                              ? icon_lg_giaitri
                              : "" || item_main.key === 7
                              ? icon_lg_thucung
                              : ""
                          }
                          alt="icon"
                          className="h-[80px] w-[80px] rounded-3xl cursor-pointer"
                        />
                      </div>
                      <p className="h-[30px] w-full flex items-center justify-center cursor-pointer">
                        {item_main.label}
                      </p>
                    </div>
                  );
                })}
            </div>
            <div className="h-[50%] w-full flex items-center">
              {danhmuc &&
                danhmuc.slice(4, 8).map((item_main: danhmuc) => {
                  return (
                    <div
                      key={item_main.key}
                      className="h-full w-1/4"
                      onClick={() => router.push(`${item_main.link}`)}
                    >
                      <div className="h-[80px] w-full flex items-center justify-center">
                        <Image
                          src={
                            item_main.key === 0
                              ? icon_lg_hoctap
                              : "" || item_main.key === 1
                              ? icon_lg_xeco
                              : "" || item_main.key === 2
                              ? icon_lg_dodientu
                              : "" || item_main.key === 3
                              ? icon_lg_noithat
                              : "" || item_main.key === 4
                              ? icon_lg_tulanh
                              : "" || item_main.key === 5
                              ? icon_lg_canhan
                              : "" || item_main.key === 6
                              ? icon_lg_giaitri
                              : "" || item_main.key === 7
                              ? icon_lg_thucung
                              : ""
                          }
                          alt="icon"
                          className="h-[80px] w-[80px] rounded-3xl cursor-pointer"
                        />
                      </div>
                      <p className="h-[30px] w-full flex items-center justify-center cursor-pointer">
                        {item_main.label}
                      </p>
                    </div>
                  );
                })}
            </div>
          </div>
        </div>
      </div>
      {/* Tin đăng gần đây */}
      <div className="h-auto w-full flex items-center justify-center mt-3">
        <div className="bg-white shadow-sm h-auto max-h-[1880px] w-[960px] p-2">
          <p className="h-[30px] text-lg font-bold">Tin đăng gần đây</p>
          <div className="h-auto w-full pt-2 flex flex-wrap gap-[10px]">
            {tindang_ganday &&
              tindang_ganday.map((item: any, index: number) => {
                return (
                  <div key={index}>
                    <Display_product_vertical item={item} />
                  </div>
                );
              })}
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default Home;

// export const getServerSideProps: GetServerSideProps<Props> = async () => {
//   const response = await AllUser_API();
//   const users = response.users;

//   return {
//     props: {
//       users,
//     },
//   };
// };
