export interface xemay {
  key: number;
  label: string;
  type: string;
  dongxe: dongxe[];
}
export interface dongxe {
  key: number;
  type: string;
}

const item_listxemay: xemay[] = [
  {
    key: 1,
    label: "Honda",
    type: "honda",
    dongxe: [
      { key: 1, type: "Vision" },
      { key: 2, type: "Air Blade" },
      { key: 3, type: "SH" },
      { key: 4, type: "Wave" },
      { key: 5, type: "Winner" },
      { key: 6, type: "Winner X" },
      { key: 7, type: "SH Mode" },
      { key: 8, type: "Lead" },
      { key: 9, type: "Dream" },
      { key: 10, type: "67" },
      { key: 11, type: "@" },
      { key: 12, type: "ADV 150" },
      { key: 13, type: "Avitor" },
      { key: 14, type: "Beat" },
      { key: 15, type: "Blade" },
      { key: 16, type: "CB" },
      { key: 17, type: "CBR" },
      { key: 18, type: "CD" },
      { key: 19, type: "CG125Fi" },
      { key: 20, type: "Chaly" },
      { key: 21, type: "Citi" },
      { key: 22, type: "Click" },
      { key: 23, type: "Cub" },
      { key: 24, type: "Dylan" },
      { key: 25, type: "Forza 300" },
      { key: 26, type: "Future" },
      { key: 27, type: "KPR" },
      { key: 28, type: "Monkey" },
      { key: 29, type: "MSX 125" },
      { key: 30, type: "Nova" },
      { key: 31, type: "PCX" },
      { key: 32, type: "PS" },
      { key: 33, type: "Rebel" },
      { key: 34, type: "Shadow" },
      { key: 35, type: "Scoopy" },
      { key: 36, type: "SCR" },
      { key: 37, type: "Sonic" },
      { key: 38, type: "Spacy" },
      { key: 39, type: "Vario" },
      { key: 40, type: "Win" },
      { key: 41, type: "Dòng khác" },
    ],
  },
  {
    key: 2,
    label: "Yamaha",
    type: "yamaha",
    dongxe: [
      { key: 1, type: "Exciter" },
      { key: 2, type: "Sirius" },
      { key: 3, type: "Nvx" },
      { key: 4, type: "Janus" },
      { key: 5, type: "Nouvo" },
      { key: 6, type: "Grande" },
      { key: 7, type: "Nozza" },
      { key: 8, type: "Acruzo" },
      { key: 9, type: "Cuxi" },
      { key: 10, type: "FZ" },
      { key: 11, type: "Jupiter" },
      { key: 12, type: "Freego" },
      { key: 13, type: "Latte" },
      { key: 14, type: "Luvias" },
      { key: 15, type: "Mio" },
      { key: 16, type: "MT" },
      { key: 17, type: "NM-X" },
      { key: 18, type: "R" },
      { key: 19, type: "Taurus" },
      { key: 20, type: "TFX" },
      { key: 21, type: "Tracer" },
      { key: 22, type: "XMAX" },
      { key: 23, type: "Yass" },
      { key: 24, type: "YAZ" },
      { key: 25, type: "YB125" },
      { key: 26, type: "Dòng khác" },
    ],
  },
  {
    key: 3,
    label: "Suzuki",
    type: "suzuki",
    dongxe: [
      { key: 1, type: "Sport / Xipo" },
      { key: 2, type: "Raider" },
      { key: 3, type: "GSX" },
      { key: 4, type: "GD" },
      { key: 5, type: "Axelo" },
      { key: 6, type: "Satria" },
      { key: 7, type: "GN" },
      { key: 8, type: "GZ" },
      { key: 9, type: "Bella" },
      { key: 10, type: "Best" },
      { key: 11, type: "Crystal" },
      { key: 12, type: "EN" },
      { key: 13, type: "Epicuro" },
      { key: 14, type: "FX125" },
      { key: 15, type: "Hayate" },
      { key: 16, type: "Impulse" },
      { key: 17, type: "Intruder" },
      { key: 18, type: "Revo" },
      { key: 19, type: "Royal" },
      { key: 20, type: "Sapphire" },
      { key: 21, type: "Smash" },
      { key: 22, type: "Stinger" },
      { key: 23, type: "V-Strom" },
      { key: 24, type: "Viva" },
      { key: 25, type: "Xbike" },
      { key: 26, type: "Dòng khác" },
    ],
  },
  {
    key: 4,
    label: "SYM",
    type: "sym",
    dongxe: [
      { key: 1, type: "Husky" },
      { key: 2, type: "Attila" },
      { key: 3, type: "Shark" },
      { key: 4, type: "Wolf" },
      { key: 5, type: "Elegant" },
      { key: 6, type: "Angela" },
      { key: 7, type: "Galaxy" },
      { key: 8, type: "Bonus" },
      { key: 9, type: "Venus" },
      { key: 10, type: "Amigo" },
      { key: 11, type: "Cello" },
      { key: 12, type: "Elite" },
      { key: 13, type: "Elizabeth" },
      { key: 14, type: "Enjoy" },
      { key: 15, type: "EZ" },
      { key: 16, type: "Fiddle" },
      { key: 17, type: "Joyride" },
      { key: 18, type: "Magic" },
      { key: 19, type: "Sanda Boss" },
      { key: 20, type: "Star" },
      { key: 21, type: "Symphony" },
      { key: 22, type: "Dòng khác" },
    ],
  },
  {
    key: 5,
    label: "Kawasaki",
    type: "kawasaki",
    dongxe: [
      { key: 1, type: "Z1000" },
      { key: 2, type: "Z300" },
      { key: 3, type: "Ninja" },
      { key: 4, type: "Max" },
      { key: 5, type: "Z800" },
      { key: 6, type: "Vulcan" },
      { key: 7, type: "Z900" },
      { key: 8, type: "Estrella" },
      { key: 9, type: "Boss" },
      { key: 10, type: "Kawasaki" },
      { key: 11, type: "Kips" },
      { key: 12, type: "KSR" },
      { key: 13, type: "Leo" },
      { key: 14, type: "Versys" },
      { key: 15, type: "W175" },
      { key: 16, type: "W400" },
      { key: 17, type: "W650" },
      { key: 18, type: "W800" },
      { key: 19, type: "Z125" },
      { key: 20, type: "Z250" },
      { key: 21, type: "Z400" },
      { key: 22, type: "Z650" },
      { key: 23, type: "ZX10R" },
      { key: 24, type: "ZX6J" },
      { key: 25, type: "ZX6R" },
      { key: 26, type: "Dòng khác" },
    ],
  },
  {
    key: 6,
    label: "Piaggio",
    type: "piaggio",
    dongxe: [
      { key: 1, type: "Vespa" },
      { key: 2, type: "Liberty" },
      { key: 3, type: "Zip" },
      { key: 4, type: "LX" },
      { key: 5, type: "GTS" },
      { key: 6, type: "Fly" },
      { key: 7, type: "Sprint" },
      { key: 8, type: "Primavera" },
      { key: 9, type: "Beverly" },
      { key: 10, type: "ET8" },
      { key: 11, type: "GT" },
      { key: 12, type: "Medley" },
      { key: 13, type: "PX" },
      { key: 14, type: "Vespa S125" },
      { key: 15, type: "Dòng khác" },
    ],
  },
  {
    key: 7,
    label: "Kymco",
    type: "kymco",
    dongxe: [
      { key: 1, type: "Candy Hi" },
      { key: 2, type: "Candy S" },
      { key: 3, type: "Jockey Fi" },
      { key: 4, type: "K-Pipe" },
      { key: 5, type: "Like Fi" },
      { key: 6, type: "Like MMC" },
      { key: 7, type: "Many" },
      { key: 8, type: "Many Fi" },
      { key: 9, type: "Many Macaron Fi" },
      { key: 10, type: "Many S" },
      { key: 11, type: "People 16 Fi" },
      { key: 12, type: "People S Fi" },
      { key: 13, type: "Solona" },
      { key: 14, type: "Dòng khác" },
    ],
  },
  {
    key: 8,
    label: "BMW",
    type: "bmw",
    dongxe: [
      { key: 1, type: "C400X" },
      { key: 2, type: "C400GT" },
      { key: 3, type: "C600" },
      { key: 4, type: "C650" },
      { key: 5, type: "F800" },
      { key: 6, type: "F800GS" },
      { key: 7, type: "R nine T" },
      { key: 8, type: "R1200" },
      { key: 9, type: "S1000R" },
      { key: 10, type: "S1000RR" },
      { key: 11, type: "Dòng khác" },
    ],
  },
  {
    key: 9,
    label: "KTM",
    type: "ktm",
    dongxe: [
      { key: 1, type: "390" },
      { key: 2, type: "1190 RC8R" },
      { key: 3, type: "1290 Super Adventure" },
      { key: 4, type: "1290 Super Duke R" },
      { key: 5, type: "Duke 200" },
      { key: 6, type: "Duke 250" },
      { key: 7, type: "Duke 390" },
      { key: 8, type: "Duke 690" },
      { key: 9, type: "RC 200" },
      { key: 10, type: "RC 250" },
      { key: 11, type: "RC 390" },
      { key: 12, type: "Dòng khác" },
    ],
  },
  {
    key: 10,
    label: "Ducati",
    type: "ducati",
    dongxe: [
      { key: 1, type: "Monster" },
      { key: 2, type: "Scrambler" },
      { key: 3, type: "Hypermotard" },
      { key: 4, type: "Streetfighter" },
      { key: 5, type: "899 panigale" },
      { key: 6, type: "Diavel" },
      { key: 7, type: "1199 panigale" },
      { key: 8, type: "Multistrada" },
      { key: 9, type: "Panigale V4" },
      { key: 10, type: "Dòng khác" },
    ],
  },
  {
    key: 11,
    label: "Khác",
    type: "other",
    dongxe: [],
  },
];

export default item_listxemay;
