export interface tablet {
  key: number;
  label: string;
  type: string;
  dongmay: dongmay[];
}
export interface dongmay {
  key: number;
  type: string;
}

const item_list_tablet: tablet[] = [
  {
    key: 1,
    label: "Apple",
    type: "apple",
    dongmay: [
      { key: 1, type: "iPad 10.2 inch" },
      { key: 2, type: "iPad Air" },
      { key: 3, type: "iPad Air 2" },
      { key: 4, type: "iPad Air 3" },
      { key: 5, type: "iPad Air 4" },
      { key: 6, type: "iPad Air 5" },
      { key: 7, type: "iPad Gen 1" },
      { key: 8, type: "iPad Gen 10" },
      { key: 9, type: "iPad Gen 2" },
      { key: 10, type: "iPad Gen 3" },
      { key: 11, type: "iPad Gen 4" },
      { key: 12, type: "iPad Gen 5" },
      { key: 13, type: "iPad Gen 6" },
      { key: 14, type: "iPad Gen 7" },
      { key: 15, type: "iPad Gen 8" },
      { key: 16, type: "iPad Gen 9" },
      { key: 17, type: "iPad Mini" },
      { key: 18, type: "iPad Mini 2" },
      { key: 19, type: "iPad Mini 3" },
      { key: 20, type: "iPad Mini 4" },
      { key: 21, type: "iPad Mini 5" },
      { key: 22, type: "iPad Mini 6" },
      { key: 23, type: "iPad Mini 7.9 inch" },
      { key: 24, type: "iPad Pro 10.5 inch" },
      { key: 25, type: "iPad Pro 11 inch 2018" },
      { key: 26, type: "iPad Pro 11 inch 2020" },
      { key: 27, type: "iPad Pro 12.9 inch" },
      { key: 28, type: "iPad Pro 12.9 inch 2017" },
      { key: 29, type: "iPad Pro 12.9 inch 2018" },
      { key: 30, type: "iPad Pro 12.9 inch 2020" },
      { key: 31, type: "iPad Pro 9.7 inch" },
      { key: 32, type: "iPad Pro M1 2021" },
      { key: 33, type: "iPad Pro M2 2022" },
      { key: 34, type: "Dòng khác" },
    ],
  },
  {
    key: 2,
    label: "Samsung",
    type: "samsung",
    dongmay: [
      { key: 1, type: "Galaxy Book" },
      { key: 2, type: "Galaxy Note" },
      { key: 3, type: "Galaxy Note Pro" },
      { key: 4, type: "Galaxy Tab" },
      { key: 5, type: "Galaxy Tab 2" },
      { key: 6, type: "Galaxy Tab 3" },
      { key: 7, type: "Galaxy Tab 4" },
      { key: 8, type: "Galaxy Tab A" },
      { key: 9, type: "Galaxy Tab A 10.1 S-pen" },
      { key: 10, type: "Galaxy Tab A 8.0" },
      { key: 11, type: "Galaxy Tab A 8.4" },
      { key: 12, type: "Galaxy Tab A6" },
      { key: 13, type: "Galaxy Tab A7" },
      { key: 14, type: "Galaxy Tab A8" },
      { key: 15, type: "Galaxy Tab A8 Plus" },
      { key: 16, type: "Galaxy Tab Active Pro" },
      { key: 17, type: "Galaxy Tab E" },
      { key: 18, type: "Galaxy Tab Pro S" },
      { key: 19, type: "Galaxy Tab S" },
      { key: 20, type: "Galaxy Tab S4 10.5 S-Pen" },
      { key: 21, type: "Galaxy Tab S5e" },
      { key: 22, type: "Galaxy Tab S6" },
      { key: 23, type: "Galaxy Tab S6 Lite" },
      { key: 24, type: "Galaxy Tab S7" },
      { key: 25, type: "Galaxy Tab S7 FE" },
      { key: 26, type: "Galaxy Tab S7 Plus" },
      { key: 27, type: "Galaxy Tab S8" },
      { key: 28, type: "Galaxy Tab S8 Plus" },
      { key: 29, type: "Galaxy Tab S8 Ultra" },
      { key: 30, type: "Galaxy Tab with S Pen" },
      { key: 31, type: "Dòng khác" },
    ],
  },
  {
    key: 3,
    label: "Asus",
    type: "asus",
    dongmay: [
      { key: 1, type: "FonePad" },
      { key: 2, type: "Nexus" },
      { key: 3, type: "ZenPad" },
      { key: 4, type: "Dòng khác" },
    ],
  },
  {
    key: 4,
    label: "Huawei",
    type: "huawei",
    dongmay: [
      { key: 1, type: "MatePad" },
      { key: 2, type: "MatePad 11" },
      { key: 3, type: "MatePad T8" },
      { key: 4, type: "MediaPad M3" },
      { key: 5, type: "MediaPad M5 10" },
      { key: 6, type: "MediaPad M5 10 Pro" },
      { key: 7, type: "MediaPad M5 Lite" },
      { key: 8, type: "MediaPad M6" },
      { key: 9, type: "MediaPad T1" },
      { key: 10, type: "MediaPad T3" },
      { key: 11, type: "MediaPad T5" },
      { key: 12, type: "Dòng khác" },
    ],
  },
  {
    key: 5,
    label: "Lenovo",
    type: "lenovo",
    dongmay: [
      { key: 1, type: "Ideatab" },
      { key: 2, type: "M10 FHD REL" },
      { key: 3, type: "Phab" },
      { key: 4, type: "Phab 2" },
      { key: 5, type: "Phab 2 Plus" },
      { key: 6, type: "Phab 2 Pro" },
      { key: 7, type: "Tab 2" },
      { key: 8, type: "Tab 3" },
      { key: 9, type: "Tab 4" },
      { key: 10, type: "Tab 7" },
      { key: 11, type: "Tab 7 Essential" },
      { key: 12, type: "Tab E10" },
      { key: 13, type: "Tab E7" },
      { key: 14, type: "Tab M7" },
      { key: 15, type: "Tab M8" },
      { key: 16, type: "Tab V7" },
      { key: 17, type: "TB-7104I" },
      { key: 18, type: "TB3" },
      { key: 19, type: "Yoga book" },
      { key: 20, type: "Dòng khác" },
    ],
  },
  {
    key: 6,
    label: "Xiaomi",
    type: "xiaomi",
    dongmay: [
      { key: 1, type: "Mi Pad 2" },
      { key: 2, type: "Mi Pad 3" },
      { key: 3, type: "Mi Pad 4" },
      { key: 4, type: "Mi Pad 5" },
      { key: 5, type: "Redmi Pad" },
      { key: 6, type: "Dòng khác" },
    ],
  },
  {
    key: 7,
    label: "Acer",
    type: "acer",
    dongmay: [
      { key: 1, type: "Iconia A1-830" },
      { key: 2, type: "Iconia B1-720" },
      { key: 3, type: "Iconia B1-723" },
      { key: 4, type: "Iconia B1-740" },
      { key: 5, type: "Iconia One 7 B1-730" },
      { key: 6, type: "Iconia Tab 7 A1-713" },
      { key: 7, type: "Iconia Tab A1-810" },
      { key: 8, type: "Iconia Tab A1-811" },
      { key: 9, type: "Iconia Tab A200" },
      { key: 10, type: "Iconia Tab A3" },
      { key: 11, type: "Iconia Tab A3-A20" },
      { key: 12, type: "Iconia Tab A3-A20FHD" },
      { key: 13, type: "Iconia Tab A500" },
      { key: 14, type: "Iconia Tab A501" },
      { key: 15, type: "Iconia Tab A510" },
      { key: 16, type: "Iconia Tab A511" },
      { key: 17, type: "Iconia Tab A700" },
      { key: 18, type: "Iconia Tab A701" },
      { key: 19, type: "Iconia W1-810" },
      { key: 20, type: "Dòng khác" },
    ],
  },
  {
    key: 8,
    label: "Masstel",
    type: "masstel",
    dongmay: [
      { key: 1, type: "T712" },
      { key: 2, type: "Tab 10" },
      { key: 3, type: "Tab 10 Pro" },
      { key: 4, type: "Tab 7" },
      { key: 5, type: "Tab 7 Plus" },
      { key: 6, type: "Tab 7 Plus Kidzone" },
      { key: 7, type: "Tab 710" },
      { key: 8, type: "Tab 8" },
      { key: 9, type: "Tab 8 Plus" },
      { key: 10, type: "Tab 8 Pro" },
      { key: 11, type: "Tab 825" },
      { key: 12, type: "Dòng khác" },
    ],
  },
  {
    key: 9,
    label: "Khác",
    type: "other",
    dongmay: [],
  },
];

export default item_list_tablet;
