export interface oto {
  key: number;
  label: string;
  type: string;
  dongxe: dongxe[];
}
export interface dongxe {
  key: number;
  type: string;
}

const item_listoto: oto[] = [
  {
    key: 1,
    label: "Toyota",
    type: "toyota",
    dongxe: [
      { key: 1, type: "Vios" },
      { key: 2, type: "Fortuner" },
      { key: 3, type: "Innova" },
      { key: 4, type: "Camry" },
      { key: 5, type: "Corolla Altis" },
      { key: 6, type: "Yaris" },
      { key: 7, type: "Land Cruiser" },
      { key: 8, type: "Zace" },
      { key: 9, type: "86" },
      { key: 10, type: "4 Runner" },
      { key: 11, type: "Allion" },
      { key: 12, type: "Alphard" },
      { key: 13, type: "Altezza" },
      { key: 14, type: "Aristo" },
      { key: 15, type: "Aurion" },
      { key: 16, type: "Avalon" },
      { key: 17, type: "Avanza" },
      { key: 18, type: "Avensis" },
      { key: 19, type: "Aygo" },
      { key: 20, type: "Brevis" },
      { key: 21, type: "Caldina" },
      { key: 22, type: "Cami" },
      { key: 23, type: "Carina" },
      { key: 24, type: "Celica" },
      { key: 25, type: "Century" },
      { key: 26, type: "Chaser" },
      { key: 27, type: "Corolla" },
      { key: 28, type: "Corolla Cross" },
      { key: 29, type: "Corona" },
      { key: 30, type: "Cressida" },
      { key: 31, type: "Cresta" },
      { key: 32, type: "Crown" },
      { key: 33, type: "Estima" },
      { key: 34, type: "Fj cruiser" },
      { key: 35, type: "Hiace" },
      { key: 36, type: "Highlander" },
      { key: 37, type: "Hilux" },
      { key: 38, type: "Ipsum" },
      { key: 39, type: "IQ" },
      { key: 40, type: "Land Cruiser Prado" },
      { key: 41, type: "Liteace" },
      { key: 42, type: "Mark II" },
      { key: 43, type: "Matrix" },
      { key: 44, type: "Mega cruiser" },
      { key: 45, type: "MR 2" },
      { key: 46, type: "Picnic" },
      { key: 47, type: "Platz" },
      { key: 48, type: "Prado" },
      { key: 49, type: "Previa" },
      { key: 50, type: "Prius" },
      { key: 51, type: "Progres" },
      { key: 52, type: "Raum" },
      { key: 53, type: "RAV4" },
      { key: 54, type: "Rush" },
      { key: 55, type: "Sequoia" },
      { key: 56, type: "Sera" },
      { key: 57, type: "Sienna" },
      { key: 58, type: "Soarer" },
      { key: 59, type: "Solara" },
      { key: 60, type: "Starlet" },
      { key: 61, type: "Supra" },
      { key: 62, type: "Tacoma" },
      { key: 63, type: "Tercel" },
      { key: 64, type: "Townace" },
      { key: 65, type: "Tundra" },
      { key: 66, type: "Venza" },
      { key: 67, type: "Verossa" },
      { key: 68, type: "Vista" },
      { key: 69, type: "Wigo" },
      { key: 70, type: "Wish" },
      { key: 71, type: "XA" },
      { key: 72, type: "Yaris Verso" },
      { key: 73, type: "Dòng khác" },
    ],
  },
  {
    key: 2,
    label: "Ford",
    type: "ford",
    dongxe: [
      { key: 1, type: "Ranger" },
      { key: 2, type: "EcoSport" },
      { key: 3, type: "Everest" },
      { key: 4, type: "Focus" },
      { key: 5, type: "Transit" },
      { key: 6, type: "Escape" },
      { key: 7, type: "Laser" },
      { key: 8, type: "Fiesta" },
      { key: 9, type: "Acononline" },
      { key: 10, type: "Aerostar" },
      { key: 11, type: "Aspire" },
      { key: 12, type: "Bronco" },
      { key: 13, type: "Capri" },
      { key: 14, type: "Caravan" },
      { key: 15, type: "Cargo" },
      { key: 16, type: "Club wagon" },
      { key: 17, type: "Contour" },
      { key: 18, type: "Courier" },
      { key: 19, type: "Crown victoria" },
      { key: 20, type: "Edge" },
      { key: 21, type: "Escort" },
      { key: 22, type: "Espedition" },
      { key: 23, type: "Explorer" },
      { key: 24, type: "Express" },
      { key: 25, type: "F 150" },
      { key: 26, type: "F 350" },
      { key: 27, type: "F 450" },
      { key: 28, type: "F 700" },
      { key: 29, type: "Flex" },
      { key: 30, type: "Focus C Max" },
      { key: 31, type: "Fucion" },
      { key: 32, type: "Galaxie" },
      { key: 33, type: "Ka" },
      { key: 34, type: "Maverick" },
      { key: 35, type: "Mondeo" },
      { key: 36, type: "Mustang" },
      { key: 37, type: "Orion" },
      { key: 38, type: "Probe" },
      { key: 39, type: "Puma" },
      { key: 40, type: "Sierra" },
      { key: 41, type: "Taurus" },
      { key: 42, type: "Tempo" },
      { key: 43, type: "Tourneo" },
      { key: 44, type: "Wind star" },
      { key: 45, type: "Dòng khác" },
    ],
  },
  {
    key: 3,
    label: "Mitsubishi",
    type: "mitsubishi",
    dongxe: [
      { key: 1, type: "Pajero" },
      { key: 2, type: "Attrage" },
      { key: 3, type: "Mirage" },
      { key: 4, type: "Triton" },
      { key: 5, type: "Outlander" },
      { key: 6, type: "Jolie" },
      { key: 7, type: "Grandis" },
      { key: 8, type: "Zinger" },
      { key: 9, type: "3000GT" },
      { key: 10, type: "Airtek" },
      { key: 11, type: "Challenger" },
      { key: 12, type: "Chariot" },
      { key: 13, type: "Colt" },
      { key: 14, type: "Diamante" },
      { key: 15, type: "Dion" },
      { key: 16, type: "Eclipse" },
      { key: 17, type: "EK wagon" },
      { key: 18, type: "Galant" },
      { key: 19, type: "Grunder" },
      { key: 20, type: "GTO" },
      { key: 21, type: "Hover" },
      { key: 22, type: "IO" },
      { key: 23, type: "Jeep" },
      { key: 24, type: "L200" },
      { key: 25, type: "L300" },
      { key: 26, type: "L400" },
      { key: 27, type: "Lancer" },
      { key: 28, type: "Libero" },
      { key: 29, type: "Montero" },
      { key: 30, type: "Outlander Sport" },
      { key: 31, type: "Pajero Sport" },
      { key: 32, type: "Santamo" },
      { key: 33, type: "Savrin" },
      { key: 34, type: "Sigma" },
      { key: 35, type: "Space Gear" },
      { key: 36, type: "Starion" },
      { key: 37, type: "Veryca" },
      { key: 38, type: "Xpander" },
      { key: 39, type: "Xpander Cross" },
      { key: 40, type: "Dòng khác" },
    ],
  },
  {
    key: 4,
    label: "Hyundai",
    type: "hyundai",
    dongxe: [
      { key: 1, type: "Grand i10" },
      { key: 2, type: "Santa Fe" },
      { key: 3, type: "Accent" },
      { key: 4, type: "Atos" },
      { key: 5, type: "Avante" },
      { key: 6, type: "Azera" },
      { key: 7, type: "Centennial" },
      { key: 8, type: "Click" },
      { key: 9, type: "County" },
      { key: 10, type: "Coupe" },
      { key: 11, type: "Creta" },
      { key: 12, type: "Dynasty" },
      { key: 13, type: "Elantra" },
      { key: 14, type: "eMighty" },
      { key: 15, type: "Eon" },
      { key: 16, type: "Equus" },
      { key: 17, type: "Excel" },
      { key: 18, type: "Galloper" },
      { key: 19, type: "Genesis" },
      { key: 20, type: "Getz" },
      { key: 21, type: "Gold" },
      { key: 22, type: "Grand Starex" },
      { key: 23, type: "Grandeur" },
      { key: 24, type: "H 1" },
      { key: 25, type: "i20" },
      { key: 26, type: "i30" },
      { key: 27, type: "i40" },
      { key: 28, type: "Innovation" },
      { key: 29, type: "Kona" },
      { key: 30, type: "Lantra" },
      { key: 31, type: "Lavita" },
      { key: 32, type: "Libero" },
      { key: 33, type: "Maxcruz" },
      { key: 34, type: "Mighty" },
      { key: 35, type: "Pony" },
      { key: 36, type: "S coupe" },
      { key: 37, type: "Sonata" },
      { key: 38, type: "Sota" },
      { key: 39, type: "Starex" },
      { key: 40, type: "Terracan" },
      { key: 41, type: "Tiburon" },
      { key: 42, type: "Trajet" },
      { key: 43, type: "Tucson" },
      { key: 44, type: "Tuscani" },
      { key: 45, type: "Universe" },
      { key: 46, type: "Universe Xpress Luxury" },
      { key: 47, type: "Veloster" },
      { key: 48, type: "Veracruz" },
      { key: 49, type: "Verna" },
      { key: 50, type: "Xcent" },
      { key: 51, type: "XG" },
      { key: 52, type: "Solati" },
      { key: 53, type: "Dòng khác" },
    ],
  },
  {
    key: 5,
    label: "Honda",
    type: "honda",
    dongxe: [
      { key: 1, type: "City" },
      { key: 2, type: "CR V" },
      { key: 3, type: "Civic" },
      { key: 4, type: "Accord" },
      { key: 5, type: "Odyssey" },
      { key: 6, type: "Jazz" },
      { key: 7, type: "Brio" },
      { key: 8, type: "Concerto" },
      { key: 9, type: "CR X" },
      { key: 10, type: "CR Z" },
      { key: 11, type: "Domani" },
      { key: 12, type: "Element" },
      { key: 13, type: "FIT" },
      { key: 14, type: "Insight" },
      { key: 15, type: "Integra" },
      { key: 16, type: "Legend" },
      { key: 17, type: "Life" },
      { key: 18, type: "Mobilo" },
      { key: 19, type: "NSX" },
      { key: 20, type: "Passport" },
      { key: 21, type: "Pilot" },
      { key: 22, type: "Prelude" },
      { key: 23, type: "S2000" },
      { key: 24, type: "Shuttle" },
      { key: 25, type: "Stream" },
      { key: 26, type: "Torneo" },
      { key: 27, type: "Vigor" },
      { key: 28, type: "Z" },
      { key: 29, type: "HR-V" },
      { key: 30, type: "BR-V" },
      { key: 31, type: "Dòng khác" },
    ],
  },
  {
    key: 6,
    label: "Mercedes-Benz",
    type: "mercedes",
    dongxe: [
      { key: 1, type: "C Class" },
      { key: 2, type: "S Class" },
      { key: 3, type: "GLC" },
      { key: 4, type: "GLB" },
      { key: 5, type: "E Class" },
      { key: 6, type: "Sprinter" },
      { key: 7, type: "GLK Class" },
      { key: 8, type: "GL Class" },
      { key: 9, type: "190" },
      { key: 10, type: "A Class" },
      { key: 11, type: "Atego" },
      { key: 12, type: "B Class" },
      { key: 13, type: "CL Class" },
      { key: 14, type: "CLA Class" },
      { key: 15, type: "CLK Class" },
      { key: 16, type: "CLS Class" },
      { key: 17, type: "G Class" },
      { key: 18, type: "GLA Class" },
      { key: 19, type: "GLC Class" },
      { key: 20, type: "GLE Class" },
      { key: 21, type: "GLS Class" },
      { key: 22, type: "M Class" },
      { key: 23, type: "Maybach" },
      { key: 24, type: "MB" },
      { key: 25, type: "ML Class" },
      { key: 26, type: "R Class" },
      { key: 27, type: "SL Class" },
      { key: 28, type: "SLK Class" },
      { key: 29, type: "SLR Mclaren" },
      { key: 30, type: "SR Class" },
      { key: 31, type: "V Class" },
      { key: 32, type: "Vaneo" },
      { key: 33, type: "Viano" },
      { key: 34, type: "Vito" },
      { key: 35, type: "Dòng khác" },
    ],
  },
  {
    key: 7,
    label: "KIA",
    type: "kia",
    dongxe: [
      { key: 1, type: "Morning" },
      { key: 2, type: "Rio" },
      { key: 3, type: "K3" },
      { key: 4, type: "Cerato" },
      { key: 5, type: "Forte" },
      { key: 6, type: "Sedona" },
      { key: 7, type: "Rondo" },
      { key: 8, type: "Carens" },
      { key: 9, type: "Avella" },
      { key: 10, type: "Cadenza" },
      { key: 11, type: "Carnival" },
      { key: 12, type: "Cerato Koup" },
      { key: 13, type: "CD5" },
      { key: 14, type: "Clarus" },
      { key: 15, type: "Concord" },
      { key: 16, type: "Enterprise" },
      { key: 17, type: "Jeep" },
      { key: 18, type: "Joice" },
      { key: 19, type: "K5" },
      { key: 20, type: "K7" },
      { key: 21, type: "Lotze" },
      { key: 22, type: "Magentis" },
      { key: 23, type: "Opirus" },
      { key: 24, type: "Optima" },
      { key: 25, type: "Picanto" },
      { key: 26, type: "Potentia" },
      { key: 27, type: "Pregio" },
      { key: 28, type: "Pride" },
      { key: 29, type: "Quoris" },
      { key: 30, type: "Ray" },
      { key: 31, type: "Retona" },
      { key: 32, type: "Roadster" },
      { key: 33, type: "Seltos" },
      { key: 34, type: "Sephia" },
      { key: 35, type: "Sorento" },
      { key: 36, type: "Soul" },
      { key: 37, type: "Soluto" },
      { key: 38, type: "Spectra" },
      { key: 39, type: "Sportage" },
      { key: 40, type: "Visto" },
      { key: 41, type: "Dòng khác" },
    ],
  },
  {
    key: 8,
    label: "Mazda",
    type: "mazda",
    dongxe: [
      { key: 1, type: "3" },
      { key: 2, type: "2" },
      { key: 3, type: "CX 5" },
      { key: 4, type: "MX 6" },
      { key: 5, type: "BT 50" },
      { key: 6, type: "CX 9" },
      { key: 7, type: "CX 3" },
      { key: 8, type: "323" },
      { key: 9, type: "5" },
      { key: 10, type: "6" },
      { key: 11, type: "626" },
      { key: 12, type: "929" },
      { key: 13, type: "323F" },
      { key: 14, type: "Atenza" },
      { key: 15, type: "AZ" },
      { key: 16, type: "B series" },
      { key: 17, type: "Carol" },
      { key: 18, type: "CX 7" },
      { key: 19, type: "CX 8" },
      { key: 20, type: "Eunos" },
      { key: 21, type: "Millenia" },
      { key: 22, type: "MPV" },
      { key: 23, type: "MX 3" },
      { key: 24, type: "MX 5" },
      { key: 25, type: "Pickup" },
      { key: 26, type: "Premacy" },
      { key: 27, type: "RX 7" },
      { key: 28, type: "RX 8" },
      { key: 29, type: "Tribute" },
      { key: 30, type: "Xedos 9" },
      { key: 31, type: "Dòng khác" },
    ],
  },
  {
    key: 9,
    label: "Vinfast",
    type: "vinfast",
    dongxe: [
      { key: 1, type: "Fadil" },
      { key: 2, type: "Lux" },
      { key: 3, type: "President" },
      { key: 4, type: "Dòng khác" },
    ],
  },
  {
    key: 10,
    label: "Audi",
    type: "audi",
    dongxe: [
      { key: 1, type: "80" },
      { key: 2, type: "90" },
      { key: 3, type: "100" },
      { key: 4, type: "200" },
      { key: 5, type: "A1" },
      { key: 6, type: "A2" },
      { key: 7, type: "A3" },
      { key: 8, type: "A4" },
      { key: 9, type: "A5" },
      { key: 10, type: "A6" },
      { key: 11, type: "A7" },
      { key: 12, type: "A8" },
      { key: 13, type: "Cabriolet" },
      { key: 14, type: "Coupe" },
      { key: 15, type: "Q2" },
      { key: 16, type: "Q3" },
      { key: 17, type: "Q5" },
      { key: 18, type: "Q7" },
      { key: 19, type: "Quattro" },
      { key: 20, type: "R8" },
      { key: 21, type: "RS" },
      { key: 22, type: "S8" },
      { key: 23, type: "TT" },
      { key: 24, type: "V8" },
      { key: 25, type: "Dòng khác" },
    ],
  },
  {
    key: 11,
    label: "Khác",
    type: "other",
    dongxe: [],
  },
];

export default item_listoto;
