export interface phonebrand {
  key: number;
  label: string;
  type: string;
  dongmay: dongmay[];
}
export interface dongmay {
  key: number;
  type: string;
}

const item_listphone: phonebrand[] = [
  {
    key: 1,
    label: "Apple",
    type: "apple",
    dongmay: [
      {
        key: 1,
        type: "iPhone 14 Pro Max",
      },
      {
        key: 2,
        type: "iPhone 14 Pro",
      },
      {
        key: 3,
        type: "iPhone 14",
      },
      {
        key: 4,
        type: "iPhone 14 Mini",
      },
      {
        key: 5,
        type: "iPhone 13 Pro Max",
      },
      {
        key: 6,
        type: "iPhone 13 Pro",
      },
      {
        key: 7,
        type: "iPhone 13",
      },
      {
        key: 8,
        type: "iPhone 13 Mini",
      },
      {
        key: 9,
        type: "iPhone 12 Pro Max",
      },
      {
        key: 10,
        type: "iPhone 12 Pro",
      },
      {
        key: 11,
        type: "iPhone 12",
      },
      {
        key: 12,
        type: "iPhone 12 Mini",
      },
      {
        key: 13,
        type: "iPhone SE (2022)",
      },
      {
        key: 14,
        type: "iPhone 11 Pro Max",
      },
      {
        key: 15,
        type: "iPhone 11 Pro",
      },
      {
        key: 16,
        type: "iPhone 11",
      },
      {
        key: 17,
        type: "iPhone XS Max",
      },
      {
        key: 18,
        type: "iPhone XS",
      },
      {
        key: 19,
        type: "iPhone XR",
      },
      {
        key: 20,
        type: "iPhone X",
      },
      {
        key: 21,
        type: "iPhone 8 Plus",
      },
      {
        key: 22,
        type: "iPhone 8",
      },
      {
        key: 23,
        type: "iPhone 7 Plus",
      },
      {
        key: 24,
        type: "iPhone 7",
      },
      {
        key: 25,
        type: "iPhone 6S Plus",
      },
      {
        key: 26,
        type: "iPhone 6S",
      },
      {
        key: 27,
        type: "iPhone 6 Plus",
      },
      {
        key: 28,
        type: "iPhone 6",
      },
      {
        key: 29,
        type: "iPhone 5S",
      },
      {
        key: 30,
        type: "iPhone 5C",
      },
      {
        key: 31,
        type: "iPhone 5",
      },
      { key: 32, type: "Dòng khác" },
    ],
  },
  {
    key: 2,
    label: "Samsung",
    type: "samsung",
    dongmay: [
      { key: 1, type: "Galaxy A02s" },
      { key: 2, type: "Galaxy A10" },
      { key: 3, type: "Galaxy A10 Plus" },
      { key: 4, type: "Galaxy A10 Pro" },
      { key: 5, type: "Galaxy A10S" },
      { key: 6, type: "Galaxy A11" },
      { key: 7, type: "Galaxy A12" },
      { key: 8, type: "Galaxy A13" },
      { key: 9, type: "Galaxy A20" },
      { key: 10, type: "Galaxy A20s" },
      { key: 11, type: "Galaxy A21" },
      { key: 12, type: "Galaxy A21s" },
      { key: 13, type: "Galaxy A22" },
      { key: 14, type: "Galaxy A23" },
      { key: 15, type: "Galaxy A3" },
      { key: 16, type: "Galaxy A30" },
      { key: 17, type: "Galaxy A31" },
      { key: 18, type: "Galaxy A32" },
      { key: 19, type: "Galaxy A33" },
      { key: 20, type: "Galaxy A34" },
      { key: 21, type: "Galaxy A40S" },
      { key: 22, type: "Galaxy A42" },
      { key: 23, type: "Galaxy A5" },
      { key: 24, type: "Galaxy A50" },
      { key: 25, type: "Galaxy A51" },
      { key: 26, type: "Galaxy A52" },
      { key: 27, type: "Galaxy A52s" },
      { key: 28, type: "Galaxy A53" },
      { key: 29, type: "Galaxy A54" },
      { key: 30, type: "Galaxy A6" },
      { key: 31, type: "Galaxy A6 Plus" },
      { key: 32, type: "Galaxy A60" },
      { key: 33, type: "Galaxy A6S" },
      { key: 34, type: "Galaxy A7" },
      { key: 35, type: "Galaxy A7 Plus" },
      { key: 36, type: "Galaxy A7 Star" },
      { key: 37, type: "Galaxy A70" },
      { key: 38, type: "Galaxy A71" },
      { key: 39, type: "Galaxy A72" },
      { key: 40, type: "Galaxy A720" },
      { key: 41, type: "Galaxy A73" },
      { key: 42, type: "Galaxy A8" },
      { key: 43, type: "Galaxy A8 Plus" },
      { key: 44, type: "Galaxy A8 Pro" },
      { key: 45, type: "Galaxy A8 Star" },
      { key: 46, type: "Galaxy A80" },
      { key: 47, type: "Galaxy A800F" },
      { key: 48, type: "Galaxy A82" },
      { key: 49, type: "Galaxy A8S" },
      { key: 50, type: "Galaxy A9" },
      { key: 51, type: "Galaxy A9 Plus" },
      { key: 52, type: "Galaxy A9 Pro" },
      { key: 53, type: "Galaxy A9 Star/A9 Star Lite" },
      { key: 54, type: "Galaxy A90" },
      { key: 55, type: "Galaxy A9S" },
      { key: 56, type: "Galaxy Alpha" },
      { key: 57, type: "Galaxy C5 Pro" },
      { key: 58, type: "Galaxy C7" },
      { key: 59, type: "Galaxy C7 Pro" },
      { key: 60, type: "Galaxy C8" },
      { key: 61, type: "Galaxy C9" },
      { key: 62, type: "Galaxy C9 Pro" },
      { key: 63, type: "Galaxy Core Prime" },
      { key: 64, type: "Galaxy E5" },
      { key: 65, type: "Galaxy E7" },
      { key: 66, type: "Galaxy Grand 2" },
      { key: 67, type: "Galaxy Grand Duos" },
      { key: 68, type: "Galaxy Grand Max" },
      { key: 69, type: "Galaxy Grand Prime G531" },
      { key: 70, type: "Galaxy Grand Prime G531H" },
      { key: 71, type: "Galaxy J" },
      { key: 72, type: "Galaxy J1" },
      { key: 73, type: "Galaxy J1 mini" },
      { key: 74, type: "Galaxy J1 Prime" },
      { key: 75, type: "Galaxy J2" },
      { key: 76, type: "Galaxy J2 Core" },
      { key: 77, type: "Galaxy J2 Prime" },
      { key: 78, type: "Galaxy J2 Pro" },
      { key: 79, type: "Galaxy J3" },
      { key: 80, type: "Galaxy J3 Prime" },
      { key: 81, type: "Galaxy J3 Pro" },
      { key: 82, type: "Galaxy J4" },
      { key: 83, type: "Galaxy J4 Core" },
      { key: 84, type: "Galaxy J4 Plus" },
      { key: 85, type: "Galaxy J4 pro" },
      { key: 86, type: "Galaxy J400" },
      { key: 87, type: "Galaxy J400F" },
      { key: 88, type: "Galaxy J4Prime" },
      { key: 89, type: "Galaxy J5" },
      { key: 90, type: "Galaxy J5 Prime" },
      { key: 91, type: "Galaxy J5 Pro" },
      { key: 92, type: "Galaxy J500H" },
      { key: 93, type: "Galaxy J510" },
      { key: 94, type: "Galaxy J6" },
      { key: 95, type: "Galaxy J6 plus" },
      { key: 96, type: "Galaxy J6 Prime" },
      { key: 97, type: "Galaxy J6 Pro" },
      { key: 98, type: "Galaxy J600" },
      { key: 99, type: "Galaxy J600G" },
      { key: 100, type: "Galaxy J7" },
      { key: 101, type: "Galaxy J7 Core" },
      { key: 102, type: "Galaxy J7 Duo" },
      { key: 103, type: "Galaxy J7 Max" },
      { key: 104, type: "Galaxy J7 Plus" },
      { key: 105, type: "Galaxy J7 Prime" },
      { key: 106, type: "Galaxy J7 Prime 2" },
      { key: 107, type: "Galaxy J7 Pro" },
      { key: 108, type: "Galaxy J8" },
      { key: 109, type: "Galaxy J8 plus" },
      { key: 110, type: "Galaxy J810" },
      { key: 111, type: "Galaxy J9" },
      { key: 112, type: "Galaxy J9 Pro" },
      { key: 113, type: "Galaxy M10" },
      { key: 114, type: "Galaxy M11" },
      { key: 115, type: "Galaxy M12" },
      { key: 116, type: "Galaxy M20" },
      { key: 117, type: "Galaxy M21" },
      { key: 118, type: "Galaxy M23" },
      { key: 119, type: "Galaxy M30" },
      { key: 120, type: "Galaxy M30s" },
      { key: 121, type: "Galaxy M31" },
      { key: 122, type: "Galaxy M32" },
      { key: 123, type: "Galaxy M50" },
      { key: 124, type: "Galaxy M51" },
      { key: 125, type: "Galaxy M52" },
      { key: 126, type: "Galaxy M53" },
      { key: 127, type: "Galaxy M54" },
      { key: 128, type: "Galaxy Note" },
      { key: 129, type: "Galaxy Note 10" },
      { key: 130, type: "Galaxy Note 10 Lite" },
      { key: 131, type: "Galaxy Note 10 Plus" },
      { key: 132, type: "Galaxy Note 2" },
      { key: 133, type: "Galaxy Note 20" },
      { key: 134, type: "Galaxy Note 20 Ultra" },
      { key: 135, type: "Galaxy Note 3" },
      { key: 136, type: "Galaxy Note 3 Neo" },
      { key: 137, type: "Galaxy Note 4" },
      { key: 138, type: "Galaxy Note 5" },
      { key: 139, type: "Galaxy Note 7" },
      { key: 140, type: "Galaxy Note 8" },
      { key: 141, type: "Galaxy Note 9" },
      { key: 142, type: "Galaxy Note Edge" },
      { key: 143, type: "Galaxy Note Fan Edition" },
      { key: 144, type: "Galaxy On5" },
      { key: 145, type: "Galaxy On7" },
      { key: 146, type: "Galaxy On7 Prime" },
      { key: 147, type: "Galaxy On7 Pro" },
      { key: 148, type: "Galaxy Prime G530" },
      { key: 149, type: "Galaxy S" },
      { key: 150, type: "Galaxy S Duos" },
      { key: 151, type: "Galaxy S Duos 3" },
      { key: 152, type: "Galaxy S10" },
      { key: 153, type: "Galaxy S10 Lite" },
      { key: 154, type: "Galaxy S10 plus" },
      { key: 155, type: "Galaxy S10 X" },
      { key: 156, type: "Galaxy S10E" },
      { key: 157, type: "Galaxy S2" },
      { key: 158, type: "Galaxy S20" },
      { key: 159, type: "Galaxy S20 FE" },
      { key: 160, type: "Galaxy S20 Plus" },
      { key: 161, type: "Galaxy S20 Ultra" },
      { key: 162, type: "Galaxy S21" },
      { key: 163, type: "Galaxy S21 FE" },
      { key: 164, type: "Galaxy S21 Plus" },
      { key: 165, type: "Galaxy S21 Ultra" },
      { key: 166, type: "Galaxy S22" },
      { key: 167, type: "Galaxy S22 Plus" },
      { key: 168, type: "Galaxy S22 Ultra" },
      { key: 169, type: "Galaxy S23" },
      { key: 170, type: "Galaxy S23 Plus" },
      { key: 171, type: "Galaxy S23 Ultra" },
      { key: 172, type: "Galaxy S3" },
      { key: 173, type: "Galaxy S4" },
      { key: 174, type: "Galaxy S5" },
      { key: 175, type: "Galaxy S6" },
      { key: 176, type: "Galaxy S6 Edge" },
      { key: 177, type: "Galaxy S6 Edge Plus" },
      { key: 178, type: "Galaxy S6 plus" },
      { key: 179, type: "Galaxy S7" },
      { key: 180, type: "Galaxy S7 Edge" },
      { key: 181, type: "Galaxy S8" },
      { key: 182, type: "Galaxy S8 Active" },
      { key: 183, type: "Galaxy S8 Plus" },
      { key: 184, type: "Galaxy S9" },
      { key: 185, type: "Galaxy S9 Plus" },
      { key: 186, type: "Galaxy trend plus" },
      { key: 187, type: "Galaxy Xcover 4" },
      { key: 188, type: "Galaxy Xcover 5" },
      { key: 189, type: "Galaxy Z Flip" },
      { key: 190, type: "Galaxy Z Flip2" },
      { key: 191, type: "Galaxy Z Flip3" },
      { key: 192, type: "Galaxy Z Flip4" },
      { key: 193, type: "Galaxy Z Flip5" },
      { key: 194, type: "Galaxy Z Fold" },
      { key: 195, type: "Galaxy Z Fold2" },
      { key: 196, type: "Galaxy Z Fold3" },
      { key: 197, type: "Galaxy Z Fold4" },
      { key: 198, type: "Galaxy Z Fold5" },
      { key: 199, type: "Dòng khác" },
    ],
  },
  {
    key: 3,
    label: "Huawei",
    type: "huawei",
    dongmay: [
      { key: 1, type: "8X Max" },
      { key: 2, type: "Ascend G610" },
      { key: 3, type: "Camon 12 Pro" },
      { key: 4, type: "Camon 15 Air" },
      { key: 5, type: "Enjoy 5S" },
      { key: 6, type: "Enjoy 6" },
      { key: 7, type: "Enjoy 7 Plus" },
      { key: 8, type: "Enjoy 7S" },
      { key: 9, type: "Enjoy 8" },
      { key: 10, type: "Enjoy 9" },
      { key: 11, type: "Enjoy 9 Plus" },
      { key: 12, type: "Enjoy 9E" },
      { key: 13, type: "Enjoy Max" },
      { key: 14, type: "G Play Mini" },
      { key: 15, type: "G7 Plus" },
      { key: 16, type: "G9 Lite" },
      { key: 17, type: "GR5 2017" },
      { key: 18, type: "GR5/GR5 Mini" },
      { key: 19, type: "Honor 10" },
      { key: 20, type: "Honor 10 Lite" },
      { key: 21, type: "Honor 7A" },
      { key: 22, type: "Honor 7C" },
      { key: 23, type: "Honor 7X" },
      { key: 24, type: "Honor 8X" },
      { key: 25, type: "Honor 8X max" },
      { key: 26, type: "Honor 9" },
      { key: 27, type: "Honor 9 Lite" },
      { key: 28, type: "Honor Magic 2" },
      { key: 29, type: "Honor Note 10" },
      { key: 30, type: "Honor Note 8" },
      { key: 31, type: "Honor Play" },
      { key: 32, type: "Honor Play 3e" },
      { key: 33, type: "Honor V8" },
      { key: 34, type: "Honor View 10" },
      { key: 35, type: "Honor View 20" },
      { key: 36, type: "Mate 10" },
      { key: 37, type: "Mate 20" },
      { key: 38, type: "Mate 20 Lite" },
      { key: 39, type: "Mate 20 Pro" },
      { key: 40, type: "Mate 20 RS Porsche Design" },
      { key: 41, type: "Mate 20X" },
      { key: 42, type: "Mate 30 Pro" },
      { key: 43, type: "Mate 40" },
      { key: 44, type: "Mate 40 Pro" },
      { key: 45, type: "Mate 8" },
      { key: 46, type: "Mate 9" },
      { key: 47, type: "Mate 9 Pro" },
      { key: 48, type: "Mate SE" },
      { key: 49, type: "Mate X" },
      { key: 50, type: "Nexus 6P" },
      { key: 51, type: "Nova 2 Lite" },
      { key: 52, type: "Nova 2 Plus" },
      { key: 53, type: "Nova 2i" },
      { key: 54, type: "Nova 2S" },
      { key: 55, type: "Nova 3" },
      { key: 56, type: "Nova 3e" },
      { key: 57, type: "Nova 3i" },
      { key: 58, type: "Nova 4e" },
      { key: 59, type: "Nova 4i" },
      { key: 60, type: "Nova 5" },
      { key: 61, type: "Nova 5 Pro" },
      { key: 62, type: "Nova 5i" },
      { key: 63, type: "Nova 5T" },
      { key: 64, type: "Nova 7" },
      { key: 65, type: "Nova 7i" },
      { key: 66, type: "Nova Lite" },
      { key: 67, type: "Nova Lite 2" },
      { key: 68, type: "Nova Lite 3" },
      { key: 69, type: "Nova Plus" },
      { key: 70, type: "P Smart" },
      { key: 71, type: "P Smart Z" },
      { key: 72, type: "P10" },
      { key: 73, type: "P10 Lite" },
      { key: 74, type: "P10 Plus" },
      { key: 75, type: "P11" },
      { key: 76, type: "P20 Lite" },
      { key: 77, type: "P20 Plus" },
      { key: 78, type: "P20 Pro" },
      { key: 79, type: "P30" },
      { key: 80, type: "P30 Lite" },
      { key: 81, type: "P30 Pro" },
      { key: 82, type: "P40" },
      { key: 83, type: "P40 Pro" },
      { key: 84, type: "P50" },
      { key: 85, type: "P50 Pro" },
      { key: 86, type: "P60" },
      { key: 87, type: "P60 Art" },
      { key: 88, type: "P60 Pro" },
      { key: 89, type: "P8 Lite" },
      { key: 90, type: "P9" },
      { key: 91, type: "P9 Plus" },
      { key: 92, type: "Pouvoir 3" },
      { key: 93, type: "Spark Go" },
      { key: 94, type: "Y3" },
      { key: 95, type: "Y3II" },
      { key: 96, type: "Y5" },
      { key: 97, type: "Y5 Lite" },
      { key: 98, type: "Y5 Prime" },
      { key: 99, type: "Y541" },
      { key: 100, type: "Y5II" },
      { key: 101, type: "Y6" },
      { key: 102, type: "Y6 Prime" },
      { key: 103, type: "Y6 Pro" },
      { key: 104, type: "Y6II CAM-L21" },
      { key: 105, type: "Y7" },
      { key: 106, type: "Y7 Prime" },
      { key: 107, type: "Y7 Pro" },
      { key: 108, type: "Y9" },
      { key: 109, type: "Y9 Prime" },
      { key: 110, type: "Y9 Pro" },
      { key: 111, type: "Dòng khác" },
    ],
  },
  {
    key: 4,
    label: "Oppo",
    type: "oppo",
    dongmay: [
      { key: 1, type: "1201" },
      { key: 2, type: "1803" },
      { key: 3, type: "1825" },
      { key: 4, type: "A11W" },
      { key: 5, type: "A12" },
      { key: 6, type: "A15" },
      { key: 7, type: "A15s" },
      { key: 8, type: "A16" },
      { key: 9, type: "A16K" },
      { key: 10, type: "A1K" },
      { key: 11, type: "A3" },
      { key: 12, type: "A30" },
      { key: 13, type: "A31" },
      { key: 14, type: "A32" },
      { key: 15, type: "A33" },
      { key: 16, type: "A33W" },
      { key: 17, type: "A35" },
      { key: 18, type: "A37" },
      { key: 19, type: "A37F" },
      { key: 20, type: "A37FW" },
      { key: 21, type: "A39" },
      { key: 22, type: "A3S" },
      { key: 23, type: "A5" },
      { key: 24, type: "A51" },
      { key: 25, type: "A52" },
      { key: 26, type: "A53" },
      { key: 27, type: "A54" },
      { key: 28, type: "A55" },
      { key: 29, type: "A57" },
      { key: 30, type: "A59" },
      { key: 31, type: "A59S" },
      { key: 32, type: "A5S" },
      { key: 33, type: "A7" },
      { key: 34, type: "A71" },
      { key: 35, type: "A73" },
      { key: 36, type: "A73S" },
      { key: 37, type: "A74" },
      { key: 38, type: "A75" },
      { key: 39, type: "A75S" },
      { key: 40, type: "A76" },
      { key: 41, type: "A77" },
      { key: 42, type: "A79" },
      { key: 43, type: "A7x" },
      { key: 44, type: "A8" },
      { key: 45, type: "A83" },
      { key: 46, type: "A9" },
      { key: 47, type: "A91" },
      { key: 48, type: "A92" },
      { key: 49, type: "A93" },
      { key: 50, type: "A94" },
      { key: 51, type: "A95" },
      { key: 52, type: "A96" },
      { key: 53, type: "A9X" },
      { key: 54, type: "Ax5" },
      { key: 55, type: "Ax5S" },
      { key: 56, type: "F1" },
      { key: 57, type: "F1 Plus" },
      { key: 58, type: "F1 Pro" },
      { key: 59, type: "F11" },
      { key: 60, type: "F11 Pro" },
      { key: 61, type: "F1s" },
      { key: 62, type: "F1W" },
      { key: 63, type: "F3 / F3 Lite" },
      { key: 64, type: "F3 Plus" },
      { key: 65, type: "F5" },
      { key: 66, type: "F5 Lite" },
      { key: 67, type: "F5 Plus" },
      { key: 68, type: "F5 Youth" },
      { key: 69, type: "F7" },
      { key: 70, type: "F7 Plus" },
      { key: 71, type: "F7 youth" },
      { key: 72, type: "F9" },
      { key: 73, type: "F9 Plus" },
      { key: 74, type: "F9 Pro" },
      { key: 75, type: "Find 5" },
      { key: 76, type: "Find 5 Mini" },
      { key: 77, type: "Find 7" },
      { key: 78, type: "Find 7A" },
      { key: 79, type: "Find 9" },
      { key: 80, type: "Find Muse" },
      { key: 81, type: "Find N" },
      { key: 82, type: "Find N2" },
      { key: 83, type: "Find N2 Flip" },
      { key: 84, type: "Find Way S" },
      { key: 85, type: "Find X" },
      { key: 86, type: "Find X2" },
      { key: 87, type: "Find X2 Pro" },
      { key: 88, type: "Find X3" },
      { key: 89, type: "Find X3 Neo" },
      { key: 90, type: "Find X3 Pro" },
      { key: 91, type: "Find X5" },
      { key: 92, type: "Find X5 Pro" },
      { key: 93, type: "Find X6" },
      { key: 94, type: "Find X6 Pro" },
      { key: 95, type: "Joy" },
      { key: 96, type: "Joy 3" },
      { key: 97, type: "Joy Plus" },
      { key: 98, type: "K1" },
      { key: 99, type: "K11" },
      { key: 100, type: "K3" },
      { key: 101, type: "Mirror 3" },
      { key: 102, type: "Mirror 5" },
      { key: 103, type: "Mirror 5S" },
      { key: 104, type: "N1" },
      { key: 105, type: "N1 Mini" },
      { key: 106, type: "N3" },
      { key: 107, type: "Neo 1" },
      { key: 108, type: "Neo 3" },
      { key: 109, type: "Neo 5" },
      { key: 110, type: "Neo 7/7s" },
      { key: 111, type: "R1" },
      { key: 112, type: "R1001" },
      { key: 113, type: "R11" },
      { key: 114, type: "R11S" },
      { key: 115, type: "R11S Plus" },
      { key: 116, type: "R13" },
      { key: 117, type: "R15" },
      { key: 118, type: "R15 Neo" },
      { key: 119, type: "R15 Plus" },
      { key: 120, type: "R15 Pro" },
      { key: 121, type: "R17" },
      { key: 122, type: "R17 Neo" },
      { key: 123, type: "R17 Pro" },
      { key: 124, type: "R19" },
      { key: 125, type: "R1K" },
      { key: 126, type: "R2001" },
      { key: 127, type: "R3" },
      { key: 128, type: "R5" },
      { key: 129, type: "R7 / R7 Lite" },
      { key: 130, type: "R7 Plus" },
      { key: 131, type: "R7s" },
      { key: 132, type: "R7sf" },
      { key: 133, type: "R8001" },
      { key: 134, type: "R8106" },
      { key: 135, type: "R821" },
      { key: 136, type: "R827" },
      { key: 137, type: "R831" },
      { key: 138, type: "R9" },
      { key: 139, type: "R9 Plus" },
      { key: 140, type: "R9S" },
      { key: 141, type: "R9S Plus" },
      { key: 142, type: "Reno" },
      { key: 143, type: "Reno 10X" },
      { key: 144, type: "Reno 10X Zoom Edition" },
      { key: 145, type: "Reno 2/2F" },
      { key: 146, type: "Reno Lite" },
      { key: 147, type: "Reno Z" },
      { key: 148, type: "Reno10" },
      { key: 149, type: "Reno10 Pro" },
      { key: 150, type: "Reno10 Pro Plus" },
      { key: 151, type: "Reno3" },
      { key: 152, type: "Reno4" },
      { key: 153, type: "Reno4 Pro" },
      { key: 154, type: "Reno5" },
      { key: 155, type: "Reno6" },
      { key: 156, type: "Reno6 Pro" },
      { key: 157, type: "Reno6 Z" },
      { key: 158, type: "Reno7" },
      { key: 159, type: "Reno7 Pro" },
      { key: 160, type: "Reno7 Z" },
      { key: 161, type: "Reno8" },
      { key: 162, type: "Reno8 Pro" },
      { key: 163, type: "Reno8 T" },
      { key: 164, type: "Reno8 Z" },
      { key: 165, type: "Reno9" },
      { key: 166, type: "Reno9 Pro" },
      { key: 167, type: "Reno9 Pro Plus" },
      { key: 168, type: "U707" },
      { key: 169, type: "X9006" },
      { key: 170, type: "Yoyo" },
      { key: 171, type: "Dòng khác" },
    ],
  },
  {
    key: 5,
    label: "Xiaomi",
    type: "xiaomi",
    dongmay: [
      { key: 1, type: "11 Lite" },
      { key: 2, type: "11T" },
      { key: 3, type: "11T Pro" },
      { key: 4, type: "12" },
      { key: 5, type: "12 Pro" },
      { key: 6, type: "12s" },
      { key: 7, type: "12T" },
      { key: 8, type: "12T Pro" },
      { key: 9, type: "12X" },
      { key: 10, type: "13" },
      { key: 11, type: "13 Lite" },
      { key: 12, type: "13 Pro" },
      { key: 13, type: "Black Shark" },
      { key: 14, type: "Black Shark 2" },
      { key: 15, type: "Black Shark 3" },
      { key: 16, type: "Black Shark 3 Pro" },
      { key: 17, type: "Black Shark 4" },
      { key: 18, type: "Black Shark 5" },
      { key: 19, type: "Black Shark Helo" },
      { key: 20, type: "Mi 1" },
      { key: 21, type: "Mi 10" },
      { key: 22, type: "Mi 10T" },
      { key: 23, type: "Mi 11" },
      { key: 24, type: "Mi 11 Lite" },
      { key: 25, type: "Mi 11 Ultra" },
      { key: 26, type: "Mi 2" },
      { key: 27, type: "Mi 3" },
      { key: 28, type: "Mi 4" },
      { key: 29, type: "Mi 4C" },
      { key: 30, type: "Mi 4S" },
      { key: 31, type: "Mi 5" },
      { key: 32, type: "Mi 5 Plus" },
      { key: 33, type: "Mi 5C" },
      { key: 34, type: "Mi 5S" },
      { key: 35, type: "Mi 5S Plus" },
      { key: 36, type: "Mi 5X" },
      { key: 37, type: "Mi 6" },
      { key: 38, type: "Mi 6 Pro" },
      { key: 39, type: "Mi 6X" },
      { key: 40, type: "Mi 7 Plus" },
      { key: 41, type: "Mi 8" },
      { key: 42, type: "Mi 8 Ee" },
      { key: 43, type: "Mi 8 Lite" },
      { key: 44, type: "Mi 8 Pro" },
      { key: 45, type: "Mi 8 SE" },
      { key: 46, type: "Mi 9" },
      { key: 47, type: "Mi 9 SE" },
      { key: 48, type: "Mi 9T" },
      { key: 49, type: "Mi 9T Pro" },
      { key: 50, type: "Mi 9X" },
      { key: 51, type: "Mi A1" },
      { key: 52, type: "Mi A2" },
      { key: 53, type: "Mi A2 Lite" },
      { key: 54, type: "Mi A3" },
      { key: 55, type: "Mi A3 Lite" },
      { key: 56, type: "Mi Max" },
      { key: 57, type: "Mi Max 1" },
      { key: 58, type: "Mi Max 2" },
      { key: 59, type: "Mi Max 2 DGW" },
      { key: 60, type: "Mi Max 3" },
      { key: 61, type: "Mi Max 3 Pro" },
      { key: 62, type: "Mi Max 4" },
      { key: 63, type: "Mi Max 4 Pro" },
      { key: 64, type: "Mi Mix" },
      { key: 65, type: "Mi Mix 2" },
      { key: 66, type: "Mi Mix 2S" },
      { key: 67, type: "Mi Mix 3" },
      { key: 68, type: "Mi Mix 4" },
      { key: 69, type: "Mi Mix Flex" },
      { key: 70, type: "Mi Note" },
      { key: 71, type: "Mi Note 10" },
      { key: 72, type: "Mi Note 10 Lite" },
      { key: 73, type: "Mi Note 10 Pro" },
      { key: 74, type: "Mi Note 2" },
      { key: 75, type: "Mi Note 3" },
      { key: 76, type: "Mi Note Pro" },
      { key: 77, type: "POCO M3" },
      { key: 78, type: "POCO M4" },
      { key: 79, type: "POCO M4 Pro" },
      { key: 80, type: "POCO M5" },
      { key: 81, type: "POCO M5s" },
      { key: 82, type: "POCO X3 GT" },
      { key: 83, type: "POCO X3 NFC" },
      { key: 84, type: "POCO X3 Pro" },
      { key: 85, type: "Redmi 10" },
      { key: 86, type: "Redmi 10A" },
      { key: 87, type: "Redmi 10C" },
      { key: 88, type: "Redmi 1S" },
      { key: 89, type: "Redmi 2" },
      { key: 90, type: "Redmi 3 Pro" },
      { key: 91, type: "Redmi 3/3S/3X" },
      { key: 92, type: "Redmi 4 Prime" },
      { key: 93, type: "Redmi 4 Pro" },
      { key: 94, type: "Redmi 4/4A/4X" },
      { key: 95, type: "Redmi 4C" },
      { key: 96, type: "Redmi 5 Plus" },
      { key: 97, type: "Redmi 5 Pro" },
      { key: 98, type: "Redmi 5/5A" },
      { key: 99, type: "Redmi 5A Prime" },
      { key: 100, type: "Redmi 5C" },
      { key: 101, type: "Redmi 6" },
      { key: 102, type: "Redmi 6 Plus" },
      { key: 103, type: "Redmi 6 Pro" },
      { key: 104, type: "Redmi 6A" },
      { key: 105, type: "Redmi 7" },
      { key: 106, type: "Redmi 7A" },
      { key: 107, type: "Redmi 8/8A" },
      { key: 108, type: "Redmi 9" },
      { key: 109, type: "Redmi 9A" },
      { key: 110, type: "Redmi 9C" },
      { key: 111, type: "Redmi 9T/K20" },
      { key: 112, type: "Redmi A1" },
      { key: 113, type: "Redmi A1 Plus" },
      { key: 114, type: "Redmi A2" },
      { key: 115, type: "Redmi A2 Plus" },
      { key: 116, type: "Redmi Go" },
      { key: 117, type: "Redmi K20 Pro" },
      { key: 118, type: "Redmi K30" },
      { key: 119, type: "Redmi K30 Pro" },
      { key: 120, type: "Redmi K30 Ultra" },
      { key: 121, type: "Redmi K40" },
      { key: 122, type: "Redmi K40 Pro" },
      { key: 123, type: "Redmi K40s" },
      { key: 124, type: "Redmi K50" },
      { key: 125, type: "Redmi K50 Pro" },
      { key: 126, type: "Redmi Note 1" },
      { key: 127, type: "Redmi Note 10" },
      { key: 128, type: "Redmi Note 10 Pro" },
      { key: 129, type: "Redmi Note 10s" },
      { key: 130, type: "Redmi Note 11" },
      { key: 131, type: "Redmi Note 11 Pro" },
      { key: 132, type: "Redmi Note 11 Pro Plus" },
      { key: 133, type: "Redmi Note 12" },
      { key: 134, type: "Redmi Note 12 Pro" },
      { key: 135, type: "Redmi Note 12 Turbo" },
      { key: 136, type: "Redmi Note 2" },
      { key: 137, type: "Redmi Note 2 Pro" },
      { key: 138, type: "Redmi Note 3" },
      { key: 139, type: "Redmi Note 3 Pro" },
      { key: 140, type: "Redmi Note 4 Pro" },
      { key: 141, type: "Redmi Note 4/4X" },
      { key: 142, type: "Redmi Note 5" },
      { key: 143, type: "Redmi Note 5 Pro" },
      { key: 144, type: "Redmi Note 5A/Note 5A Prime" },
      { key: 145, type: "Redmi Note 5X" },
      { key: 146, type: "Redmi Note 6" },
      { key: 147, type: "Redmi Note 6 Pro" },
      { key: 148, type: "Redmi Note 7" },
      { key: 149, type: "Redmi Note 7 Pro" },
      { key: 150, type: "Redmi Note 8" },
      { key: 151, type: "Redmi Note 8 Lite" },
      { key: 152, type: "Redmi Note 8 Pro" },
      { key: 153, type: "Redmi Note 8 SE" },
      { key: 154, type: "Redmi Note 9" },
      { key: 155, type: "Redmi Note 9 Pro" },
      { key: 156, type: "Redmi Note 9S" },
      { key: 157, type: "Redmi Pro" },
      { key: 158, type: "Redmi Pro 2" },
      { key: 159, type: "Redmi S2" },
      { key: 160, type: "Redmi X" },
      { key: 161, type: "Redmi X Lite" },
      { key: 162, type: "Redmi X Pro" },
      { key: 163, type: "Dòng khác" },
    ],
  },
  {
    key: 6,
    label: "Sony",
    type: "sony",
    dongmay: [
      { key: 1, type: "T2 Ultra" },
      { key: 2, type: "T2 Ultra Dual" },
      { key: 3, type: "XA1 Ultra" },
      { key: 4, type: "Xperia 1" },
      { key: 5, type: "Xperia 10" },
      { key: 6, type: "Xperia 10 Plus" },
      { key: 7, type: "Xperia 2" },
      { key: 8, type: "Xperia 3" },
      { key: 9, type: "Xperia 4" },
      { key: 10, type: "Xperia 5" },
      { key: 11, type: "Xperia Ace" },
      { key: 12, type: "Xperia Arc S" },
      { key: 13, type: "Xperia C" },
      { key: 14, type: "Xperia C1905" },
      { key: 15, type: "Xperia C2305" },
      { key: 16, type: "Xperia C3" },
      { key: 17, type: "Xperia C4/C4 Dual" },
      { key: 18, type: "Xperia C5 Ultra/C5 Ultra Dual" },
      { key: 19, type: "Xperia C6902" },
      { key: 20, type: "Xperia D2502" },
      { key: 21, type: "Xperia D6603" },
      { key: 22, type: "Xperia E" },
      { key: 23, type: "Xperia E2115" },
      { key: 24, type: "Xperia E2312" },
      { key: 25, type: "Xperia E4" },
      { key: 26, type: "Xperia E5" },
      { key: 27, type: "Xperia E5333" },
      { key: 28, type: "Xperia Edge" },
      { key: 29, type: "Xperia F3116" },
      { key: 30, type: "Xperia F3216" },
      { key: 31, type: "Xperia G3116" },
      { key: 32, type: "Xperia G3226" },
      { key: 33, type: "Xperia G3312" },
      { key: 34, type: "Xperia G3416" },
      { key: 35, type: "Xperia J" },
      { key: 36, type: "Xperia L1" },
      { key: 37, type: "Xperia L1 Dual" },
      { key: 38, type: "Xperia L2" },
      { key: 39, type: "Xperia L3" },
      { key: 40, type: "Xperia M" },
      { key: 41, type: "Xperia M2" },
      { key: 42, type: "Xperia M4" },
      { key: 43, type: "Xperia M4 Aqua" },
      { key: 44, type: "Xperia M5" },
      { key: 45, type: "Xperia M5 Dual" },
      { key: 46, type: "Xperia N1" },
      { key: 47, type: "Xperia P" },
      { key: 48, type: "Xperia T3" },
      { key: 49, type: "Xperia V" },
      { key: 50, type: "Xperia X" },
      { key: 51, type: "Xperia X Performance" },
      { key: 52, type: "Xperia X Premium" },
      { key: 53, type: "Xperia X2" },
      { key: 54, type: "Xperia Xa Dual" },
      { key: 55, type: "Xperia XA/XA Ultra" },
      { key: 56, type: "Xperia XA1" },
      { key: 57, type: "Xperia XA1 Plus" },
      { key: 58, type: "Xperia XA2 Plus" },
      { key: 59, type: "Xperia XA2 Ultra" },
      { key: 60, type: "Xperia XA3" },
      { key: 61, type: "Xperia XZ" },
      { key: 62, type: "Xperia XZ Premium" },
      { key: 63, type: "Xperia XZ Pro" },
      { key: 64, type: "Xperia XZ1" },
      { key: 65, type: "Xperia XZ1 Compact" },
      { key: 66, type: "Xperia XZ2 Premium" },
      { key: 67, type: "Xperia XZ2 Ultra" },
      { key: 68, type: "Xperia XZ2/Xperia XZ2 Compact" },
      { key: 69, type: "Xperia XZ3" },
      { key: 70, type: "Xperia XZ4" },
      { key: 71, type: "Xperia XZs" },
      { key: 72, type: "Xperia Z" },
      { key: 73, type: "Xperia Z Ultra" },
      { key: 74, type: "Xperia Z1" },
      { key: 75, type: "Xperia Z2" },
      { key: 76, type: "Xperia Z3" },
      { key: 77, type: "Xperia Z3 Compact" },
      { key: 78, type: "Xperia Z3 Plus" },
      { key: 79, type: "Xperia Z3V" },
      { key: 80, type: "Xperia Z4" },
      { key: 81, type: "Xperia Z4 Compact" },
      { key: 82, type: "Xperia Z4V" },
      { key: 83, type: "Xperia Z5" },
      { key: 84, type: "Xperia Z5 Compact" },
      { key: 85, type: "Xperia Z5 Premium" },
      { key: 86, type: "Xperia Z5 Premium Dual" },
      { key: 87, type: "Xperia Z6" },
      { key: 88, type: "Xperia Zl2" },
      { key: 89, type: "Xperia ZR" },
      { key: 90, type: "XZ Pro" },
      { key: 91, type: "XZ1 Plus" },
      { key: 92, type: "XZ1 Premium" },
      { key: 93, type: "Z5 Dual" },
      { key: 94, type: "Dòng khác" },
    ],
  },
  {
    key: 7,
    label: "Nokia",
    type: "nokia",
    dongmay: [
      { key: 1, type: "C21" },
      { key: 2, type: "C31" },
      { key: 3, type: "Edge" },
      { key: 4, type: "Lumia 1020" },
      { key: 5, type: "Lumia 1320" },
      { key: 6, type: "Lumia 1330" },
      { key: 7, type: "Lumia 1520" },
      { key: 8, type: "Lumia 420" },
      { key: 9, type: "Lumia 430" },
      { key: 10, type: "Lumia 435" },
      { key: 11, type: "Lumia 520" },
      { key: 12, type: "Lumia 525" },
      { key: 13, type: "Lumia 530" },
      { key: 14, type: "Lumia 532" },
      { key: 15, type: "Lumia 535" },
      { key: 16, type: "Lumia 540" },
      { key: 17, type: "Lumia 550" },
      { key: 18, type: "Lumia 620" },
      { key: 19, type: "Lumia 625" },
      { key: 20, type: "Lumia 630" },
      { key: 21, type: "Lumia 635" },
      { key: 22, type: "Lumia 636" },
      { key: 23, type: "Lumia 640" },
      { key: 24, type: "Lumia 640 XL" },
      { key: 25, type: "Lumia 720" },
      { key: 26, type: "Lumia 730" },
      { key: 27, type: "Lumia 735" },
      { key: 28, type: "Lumia 800" },
      { key: 29, type: "Lumia 850" },
      { key: 30, type: "Lumia 900" },
      { key: 31, type: "Lumia 909" },
      { key: 32, type: "Lumia 920" },
      { key: 33, type: "Lumia 925" },
      { key: 34, type: "Lumia 928" },
      { key: 35, type: "Lumia 930" },
      { key: 36, type: "Lumia 950" },
      { key: 37, type: "Lumia 950 XL" },
      { key: 38, type: "Lumia Cyan" },
      { key: 39, type: "X" },
      { key: 40, type: "X1" },
      { key: 41, type: "X2" },
      { key: 42, type: "X3" },
      { key: 43, type: "X5" },
      { key: 44, type: "X6" },
      { key: 45, type: "X7" },
      { key: 46, type: "XL" },
      { key: 47, type: "Dòng khác" },
    ],
  },
  {
    key: 8,
    label: "Asus",
    type: "asus",
    dongmay: [
      { key: 1, type: "ROG Phone" },
      { key: 2, type: "ROG Phone 2" },
      { key: 3, type: "ROG Phone 3" },
      { key: 4, type: "ROG Phone 5" },
      { key: 5, type: "ROG Phone 6" },
      { key: 6, type: "ROG Phone 6 Pro" },
      { key: 7, type: "ROG Phone 6D Ultimate" },
      { key: 8, type: "Zenfone 2" },
      { key: 9, type: "Zenfone 2 Laser" },
      { key: 10, type: "Zenfone 2S" },
      { key: 11, type: "Zenfone 3" },
      { key: 12, type: "Zenfone 3 Max" },
      { key: 13, type: "Zenfone 3 Selfie" },
      { key: 14, type: "Zenfone 3 Ultra" },
      { key: 15, type: "Zenfone 3 Zoom" },
      { key: 16, type: "Zenfone 3S" },
      { key: 17, type: "Zenfone 3S Max" },
      { key: 18, type: "Zenfone 4" },
      { key: 19, type: "Zenfone 4 Max" },
      { key: 20, type: "Zenfone 4 Max Pro" },
      { key: 21, type: "Zenfone 4 Pro" },
      { key: 22, type: "Zenfone 4 Selfie" },
      { key: 23, type: "Zenfone 4 Selfie Pro" },
      { key: 24, type: "Zenfone 4A" },
      { key: 25, type: "Zenfone 5" },
      { key: 26, type: "Zenfone 5 Lite" },
      { key: 27, type: "Zenfone 5 Max" },
      { key: 28, type: "Zenfone 5Q" },
      { key: 29, type: "Zenfone 5Z" },
      { key: 30, type: "Zenfone 6" },
      { key: 31, type: "Zenfone AR" },
      { key: 32, type: "Zenfone C" },
      { key: 33, type: "Zenfone Go" },
      { key: 34, type: "Zenfone Live" },
      { key: 35, type: "Zenfone Live L1" },
      { key: 36, type: "Zenfone M2" },
      { key: 37, type: "Zenfone Max" },
      { key: 38, type: "Zenfone Max Plus M1" },
      { key: 39, type: "Zenfone Max Pro" },
      { key: 40, type: "Zenfone Max Pro M1" },
      { key: 41, type: "Zenfone Max Pro M2" },
      { key: 42, type: "Zenfone Selfie" },
      { key: 43, type: "Zenfone V" },
      { key: 44, type: "Zenfone Zoom" },
      { key: 45, type: "Dòng khác" },
    ],
  },
  {
    key: 9,
    label: "Google",
    type: "google",
    dongmay: [
      { key: 1, type: "Google Pixel" },
      { key: 2, type: "Google Pixel 2" },
      { key: 3, type: "Google Pixel 2 XL" },
      { key: 4, type: "Google Pixel 3" },
      { key: 5, type: "Google Pixel 3 XL" },
      { key: 6, type: "Google Pixel XL" },
      { key: 7, type: "Nexus C" },
      { key: 8, type: "Pixel 3A" },
      { key: 9, type: "Pixel 3A XL" },
      { key: 10, type: "Pixel 4" },
      { key: 11, type: "Pixel 4 XL" },
      { key: 12, type: "Pixel 4A" },
      { key: 13, type: "Pixel 5" },
      { key: 14, type: "Pixel 6" },
      { key: 15, type: "Pixel 6 Pro" },
      { key: 16, type: "Pixel 7" },
      { key: 17, type: "Pixel 7 Pro" },
      { key: 18, type: "Dòng khác" },
    ],
  },
  {
    key: 10,
    label: "OnePlus",
    type: "oneplus",
    dongmay: [
      { key: 1, type: "10" },
      { key: 2, type: "10 Pro" },
      { key: 3, type: "10 Ultra" },
      { key: 4, type: "2" },
      { key: 5, type: "3" },
      { key: 6, type: "3T" },
      { key: 7, type: "4" },
      { key: 8, type: "5" },
      { key: 9, type: "5T" },
      { key: 10, type: "6" },
      { key: 11, type: "6T" },
      { key: 12, type: "6T McLaren" },
      { key: 13, type: "7" },
      { key: 14, type: "7 Pro" },
      { key: 15, type: "7T" },
      { key: 16, type: "8" },
      { key: 17, type: "8 Pro" },
      { key: 18, type: "9 Pro" },
      { key: 19, type: "A3000" },
      { key: 20, type: "A3003" },
      { key: 21, type: "A5000" },
      { key: 22, type: "A5010" },
      { key: 23, type: "A6000" },
      { key: 24, type: "One" },
      { key: 25, type: "X" },
      { key: 26, type: "Dòng khác" },
    ],
  },
  {
    key: 11,
    label: "HTC",
    type: "htc",
    dongmay: [
      { key: 1, type: "10" },
      { key: 2, type: "10 evo" },
      { key: 3, type: "10 pro" },
      { key: 4, type: "8x" },
      { key: 5, type: "Butterfly 2" },
      { key: 6, type: "Butterfly 3" },
      { key: 7, type: "Butterfly S" },
      { key: 8, type: "Design 625" },
      { key: 9, type: "Desire" },
      { key: 10, type: "Desire 10 Pro" },
      { key: 11, type: "Desire 12" },
      { key: 12, type: "Desire 12 Plus" },
      { key: 13, type: "Desire 19+" },
      { key: 14, type: "Desire 200" },
      { key: 15, type: "Desire 320" },
      { key: 16, type: "Desire 326G" },
      { key: 17, type: "Desire 501" },
      { key: 18, type: "Desire 510" },
      { key: 19, type: "Desire 526G" },
      { key: 20, type: "Desire 530" },
      { key: 21, type: "Desire 600" },
      { key: 22, type: "Desire 610" },
      { key: 23, type: "Desire 616" },
      { key: 24, type: "Desire 620G" },
      { key: 25, type: "Desire 626" },
      { key: 26, type: "Desire 626G" },
      { key: 27, type: "Desire 626G Plus" },
      { key: 28, type: "Desire 626S" },
      { key: 29, type: "Desire 628 dual SIM" },
      { key: 30, type: "Desire 630" },
      { key: 31, type: "Desire 728" },
      { key: 32, type: "Desire 728G" },
      { key: 33, type: "Desire 816" },
      { key: 34, type: "Desire 816G" },
      { key: 35, type: "Desire 820" },
      { key: 36, type: "Desire 820G Plus" },
      { key: 37, type: "Desire 820S" },
      { key: 38, type: "Desire 826" },
      { key: 39, type: "Desire eye" },
      { key: 40, type: "Dream" },
      { key: 41, type: "One 801E" },
      { key: 42, type: "One A9/One A9s" },
      { key: 43, type: "One E8" },
      { key: 44, type: "One E9 Dual" },
      { key: 45, type: "One E9 Plus" },
      { key: 46, type: "One M10" },
      { key: 47, type: "One M7" },
      { key: 48, type: "One M8" },
      { key: 49, type: "One M8 Eye" },
      { key: 50, type: "One M9" },
      { key: 51, type: "One M9 plus" },
      { key: 52, type: "One Max" },
      { key: 53, type: "One ME" },
      { key: 54, type: "One Mini" },
      { key: 55, type: "One Mini 2" },
      { key: 56, type: "One S" },
      { key: 57, type: "One SV" },
      { key: 58, type: "One X" },
      { key: 59, type: "One X10" },
      { key: 60, type: "One X9" },
      { key: 61, type: "Rhyme" },
      { key: 62, type: "Sensation XE" },
      { key: 63, type: "Sense" },
      { key: 64, type: "Sense 7" },
      { key: 65, type: "U Play" },
      { key: 66, type: "U Ultra/U Ultra Sapphire" },
      { key: 67, type: "U11" },
      { key: 68, type: "U11 Eyes" },
      { key: 69, type: "U11 Life" },
      { key: 70, type: "U11 Plus" },
      { key: 71, type: "U12" },
      { key: 72, type: "U12 Life" },
      { key: 73, type: "U12 Plus" },
      { key: 74, type: "U19E" },
      { key: 75, type: "Dòng khác" },
    ],
  },
  {
    key: 12,
    label: "Vsmart",
    type: "vsmart",
    dongmay: [
      { key: 1, type: "Active 1" },
      { key: 2, type: "Active 1 Plus" },
      { key: 3, type: "Active 3" },
      { key: 4, type: "Aris" },
      { key: 5, type: "Aris Pro" },
      { key: 6, type: "Joy 1" },
      { key: 7, type: "Joy 1 Plus" },
      { key: 8, type: "Joy 3" },
      { key: 9, type: "Joy 4" },
      { key: 10, type: "Live" },
      { key: 11, type: "Live 4" },
      { key: 12, type: "Star" },
      { key: 13, type: "Star 3" },
      { key: 14, type: "Star 4" },
      { key: 15, type: "Star 5" },
      { key: 16, type: "Dòng khác" },
    ],
  },
  {
    key: 13,
    label: "Vivo",
    type: "vivo",
    dongmay: [
      { key: 1, type: "15 Pro" },
      { key: 2, type: "1601" },
      { key: 3, type: "1606" },
      { key: 4, type: "1814" },
      { key: 5, type: "9X Plus" },
      { key: 6, type: "Apex" },
      { key: 7, type: "IQ00" },
      { key: 8, type: "IQ00 Neo" },
      { key: 9, type: "Nex" },
      { key: 10, type: "Nex A" },
      { key: 11, type: "Nex S" },
      { key: 12, type: "Nex2" },
      { key: 13, type: "S1" },
      { key: 14, type: "S1 Pro" },
      { key: 15, type: "U1" },
      { key: 16, type: "V1" },
      { key: 17, type: "V1 Max" },
      { key: 18, type: "V11" },
      { key: 19, type: "V11 Pro" },
      { key: 20, type: "V11i" },
      { key: 21, type: "V15" },
      { key: 22, type: "V15 Pro" },
      { key: 23, type: "V17" },
      { key: 24, type: "V20" },
      { key: 25, type: "V21" },
      { key: 26, type: "V23" },
      { key: 27, type: "V23e" },
      { key: 28, type: "V3" },
      { key: 29, type: "V3 Max" },
      { key: 30, type: "V5" },
      { key: 31, type: "V5 Plus" },
      { key: 32, type: "V5s" },
      { key: 33, type: "V7" },
      { key: 34, type: "v7 Plus" },
      { key: 35, type: "V9" },
      { key: 36, type: "V9 6GB" },
      { key: 37, type: "V9 Plus" },
      { key: 38, type: "V9 Pro" },
      { key: 39, type: "V9 Youth" },
      { key: 40, type: "V91" },
      { key: 41, type: "X20" },
      { key: 42, type: "X20 Plus" },
      { key: 43, type: "X20A" },
      { key: 44, type: "X21" },
      { key: 45, type: "X21A" },
      { key: 46, type: "X21I" },
      { key: 47, type: "X21S" },
      { key: 48, type: "X23" },
      { key: 49, type: "X27" },
      { key: 50, type: "X27 Pro" },
      { key: 51, type: "X30" },
      { key: 52, type: "X5" },
      { key: 53, type: "X5 Max" },
      { key: 54, type: "X5 Pro" },
      { key: 55, type: "X6" },
      { key: 56, type: "X60" },
      { key: 57, type: "X60 Pro" },
      { key: 58, type: "X60 Pro Plus" },
      { key: 59, type: "X6A" },
      { key: 60, type: "X6S Plus" },
      { key: 61, type: "X7" },
      { key: 62, type: "X70" },
      { key: 63, type: "X70 Pro" },
      { key: 64, type: "X70 Pro Plus" },
      { key: 65, type: "X80" },
      { key: 66, type: "X9" },
      { key: 67, type: "X9L" },
      { key: 68, type: "X9S" },
      { key: 69, type: "X9S Plus" },
      { key: 70, type: "Xshot" },
      { key: 71, type: "Y11" },
      { key: 72, type: "Y12" },
      { key: 73, type: "Y12s" },
      { key: 74, type: "Y15" },
      { key: 75, type: "Y15 Pro" },
      { key: 76, type: "Y17" },
      { key: 77, type: "Y19" },
      { key: 78, type: "Y20" },
      { key: 79, type: "Y21" },
      { key: 80, type: "Y31" },
      { key: 81, type: "Y51" },
      { key: 82, type: "Y53" },
      { key: 83, type: "Y55" },
      { key: 84, type: "Y55A" },
      { key: 85, type: "Y55s" },
      { key: 86, type: "Y65" },
      { key: 87, type: "Y66" },
      { key: 88, type: "Y67" },
      { key: 89, type: "Y69" },
      { key: 90, type: "Y71" },
      { key: 91, type: "Y75" },
      { key: 92, type: "Y79" },
      { key: 93, type: "Y8" },
      { key: 94, type: "Y81" },
      { key: 95, type: "Y81i" },
      { key: 96, type: "Y81S" },
      { key: 97, type: "Y83" },
      { key: 98, type: "Y85" },
      { key: 99, type: "Y9" },
      { key: 100, type: "Y91" },
      { key: 101, type: "Y91C" },
      { key: 102, type: "Y91i" },
      { key: 103, type: "Y93" },
      { key: 104, type: "Y93C" },
      { key: 105, type: "Y93S" },
      { key: 106, type: "Y95" },
      { key: 107, type: "Y97" },
      { key: 108, type: "Z1" },
      { key: 109, type: "Z1 Pro" },
      { key: 110, type: "Z1i" },
      { key: 111, type: "Z3" },
      { key: 112, type: "Z3X" },
      { key: 113, type: "Z5" },
      { key: 114, type: "Z5X" },
      { key: 115, type: "Dòng khác" },
    ],
  },
  {
    key: 14,
    label: "Khác",
    type: "other",
    dongmay: [],
  },
];

export default item_listphone;
